### ISSUE TITLE
Weekly Marketing Meeting Log

### ISSUE THREAD

**Issue by mrexpat** [Joystream/marketing#1]
## Meeting Date

Tuesday, November 16, 2021.

## Participants

- Bedeho
- Robert
- Ben

## Agenda
- Decide weekly marketing meeting format / lead
- Announcement of latest funding round
- Frequency, participants for AMAs / community calls
- Overarching marketing topics such as vision / "better tomorrow"
- Executing the onboarding experience + Ben's involvement

## Todo

- Set up Github project management for the onboarding
- Estimation and division of labor for onboarding
- Decide a name for this project
- Robert & Bedeho to consider what a recurring content production event could look like - a podcast? the community call? etc.
- Bedeho to introduce Robert to VCs who may have marketing resources to offer / or at least figure out the best approach to doing so (who, which channel to use, etc)
- Martin to give Robert access to Mailchimp account
- Robert & Ben to do a call and sync around executing the onboarding experience
- Robert & Ben to create a list of different "user groups"
- Robert to create a pre-call and post-call routine for community calls

## Non-action Conclusions

- Postpone decision about announcement of funding round

**Comment by robertneckelius** [comment]
I guess we can do project name suggestions here.. 

**Operation Old Spice** - they were just a product no one cared about, until they did that marketing campaign and became relevant.

Other ideas?

**Comment by robertneckelius** [comment]
## Meeting Date

Monday, December 13, 2021

## Participants

TBD

## Agenda

- Last week's todo list
- Discuss how Twitter should be used (volume/depth/quality)
- "Rank the investors"
- Superglue updates
- Handbook update
- Discuss Community manager role
- Viral loop campaign

## Non-action Conclusions

TBD

**Comment by robertneckelius** [comment]
## Meeting Date

Monday, December 20, 2021

## Participants

TBD

## Agenda

- Last week's todo list
- Superglue updates
- Hiring of community manager (https://github.com/Joystream/marketing/issues/16)
- Hiring of content creator (blog posting, tweeting, discord chats, etc)

## Todo

TBD

## Non-action Conclusions

TBD

**Comment by robertneckelius** [comment]
## Meeting Date

Monday, January 10, 2022

## Participants

- TBD
- 
## Agenda

- Last week's todo list
- Superglue updates
- Content strategy discussion (our current target audience, channels)
- Discuss coindesk PR thing
- Discuss integrators (it's time to get started on systemically sourcing and activating them)
- Discuss any other CTAs to be included in onboarding other than chat to integrator (make a membership, get tokens, etc)

## Todo

TBD

## Non-action Conclusions

TBD

**Comment by bedeho** [comment]
I can add some context here on the integrators (not sure if that wrecks this issue). But integrators are part of the duties of the HR working group, which almost certainly will be lead by @mochet. There is a question here of how we should measure the performance of this group, to make sure they are doing a good job.  There is a fundamental question here of how much detail hand-holding we should attempt to do across all DAO roles. For example, should we be enforcing the onboarding scripts the integrators use? This is very granular detail, and we do not do this for many other roles, we instead try to measure output/performance. Can we do something similar here? Recall that we also need the integrators to do their job interfacing with the new CRM, as they have to add people to this so they are now part of the FM program. A final related point is, as these two initiatives now are coupled (integrators <-> incentives 3.0), their release has to be coordinated, and its unclear when we expect either to go online just yet.

**Comment by robertneckelius** [comment]
## Meeting Date

Monday, January 17, 2022

## Participants

TBD

## Agenda

- Last week's todo list
- Superglue updates
- Helping out with Incentives 3.0

## Todo


## Non-action Conclusions

**Comment by robertneckelius** [comment]
## Meeting Date

Monday, January 24, 2022

## Participants

TBD

## Agenda

- Last week's todo list
- Superglue updates
- Referral program (can we align incentives? track automatically?)
- AMA content for this week

## Todo

- TBD

## Non-action Conclusions

**Comment by mrexpat** [comment]
## Meeting Date

Monday, February 14, 2022

## Participants

TBD

## Agenda

- Superglue updates
- Marketing Phase 1
- Referral program

## Todo

- TBD

## Non-action Conclusions

**Comment by mrexpat** [comment]
## Meeting Date

Monday, February 21, 2022

## Participants

TBD

## Agenda

- Superglue updates
- Press release next step
- Marketing next steps

## Todo


## Non-action Conclusions

N/A

**Comment by mrexpat** [comment]
## Meeting Date

Monday, February 28, 2022

## Participants

TBD

## Agenda

- Referral issue
- Marketing next steps

## Todo


## Non-action Conclusions

N/A

**Comment by mrexpat** [comment]
## Meeting Date

Monday, March 7, 2022

## Participants

TBD

## Agenda

- Last weeks tasks
- https://github.com/Joystream/marketing/issues/193

## Todo

TBD

## Non-action Conclusions

N/A

**Comment by mrexpat** [comment]
## Meeting Date

Monday, March 28, 2022

## Participants

TBD

## Agenda
- Marketing update
- Explainers for elections, proposals, bounties, creator tokens, etc
- Will add more

## Todo

## Non-action Conclusions

**Comment by mrexpat** [comment]
## Meeting Date

Monday, April 11, 2022

## Participants

TBD

## Agenda
- Marketing update
- Marketing plan

## Todo

## Non-action Conclusions

**Comment by mrexpat** [comment]
## Meeting Date

Postponed

## Participants

TBD

## Agenda

- Marketing update
- Rhodes & Ephesus
- Get Jose auth to move cards in the kanban board

## Todo


## Non-action Conclusions

**Comment by mrexpat** [comment]
## Meeting Date

Monday, April 25

## Participants



## Agenda

- Marketing update
- Discuss Joystream having work opportunities to put people into. We need to have evergreen tasks to get people going.

## Todo


## Non-action Conclusions

**Comment by mrexpat** [comment]
## Meeting Date

Monday, May 30

## Participants

TBD

## Agenda

- Marketing update
- Reserve your username campaign

## Todo


## Non-action Conclusions
