### ISSUE TITLE
Olympia release blog post

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#159]
When can draft be ready?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711118854967) by [Unito](https://www.unito.io)

**Comment by mrexpat** [comment]
@bedeho who should I talk to about the contents for it? I'd imagine 1 zoom call + 1 working day to put it together

**Comment by bedeho** [comment]
Some content will be the community side, where its unclear what we will be doing in terms of incentive 3.0 by the time the release is due, other parts will be product certainly, telling the story of what Pioneer is, explaining it, showing it etc., there certainly @thesan @dmtrjsg can be of help, and myself. I am not sure what @MattAugustynowicz has planned for the product preview, but certainly you should be part of that storytelling as well, make sure the right parts are conveyed. I am not sure what the process is there, would love to see some early plan or storyboards or something.
