### ISSUE TITLE
Update validation& nomination

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#168]
We will need to update validation and nomination tutorials to reflect that users must go to the new external apps instance which Leszek will try to prepare our ability to use.

https://github.com/Joystream/joystream/issues/3008

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201721592102644) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Closing this, as migrating and updating is covered [here](https://github.com/Joystream/joystream/issues/3179).
