### ISSUE TITLE
Incentives v3: How will creative contributions be judged?

### ISSUE THREAD

**Issue by mochet** [Joystream/marketing#170]
Someone in the RU Telegram made a good point:

_"I care about how creative initiatives will be judged. That is, if you did something not within the framework of joytasks or bounties, but brought something useful to the project. Previously, this was well evaluated in points, but now it turns out there is absolutely no motivation to invent something interesting. Yes, even just to help community members, if you are not assigned to a role involving social media management. This is a big minus of the new system, it seems to me."_

Is there any response to this at this time?

**Comment by bedeho** [comment]
If its outside the framework of bounties or work, it wont, not even spending proposals are credited in the new scheme. I guess we could incorporate the latter, and just measure value by budget, but it's not worth layering in even more complexity until we see what actually happens with the "baseline", which already quite hairy.
