### ISSUE TITLE
Network performance score spreadsheet

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#172]
Create a spreadsheet for computing network performance scores, as described by the handbook. This spreasheet will be public and long-running, and each council period will result in a new sheet being added with whatever the newest metric and result is at that time. Sheets will be linked to from the handbook, and the most recent sheet should be the default one.

**Comment by blrhc** [comment]
https://docs.google.com/spreadsheets/d/15gOnAR0ur8e0dZWDEQjX1MFzL3b_W4S3Eor7pHPOEqc/edit?usp=sharing

@bwhm may want to heavily edit or improve this!
