### ISSUE TITLE
Proposal: Referral Program 2.0

### ISSUE THREAD

**Issue by mrexpat** [Joystream/marketing#174]
Based on the marketing team's lengthy discussion here's my proposal for a referral program that aims to be highly effective in attracting relevant contributors to the Joystream project.

To be clear, I am not yet saying this is what we SHOULD do, but this is how I'd design the referral program if we decided to commit to it. Whether or not to execute this depends on what that would cost in terms of time, resources, and so on.

## What is the problem we are solving?

At this time, Joystream is seeking the attention of people who wish to come and contribute to our project. In the grand scheme of things, this audience is relatively small compared to let's say all the people who speculate on cryptocurrencies.

It also has further constraints in that we believe people commit to different protocols to various degrees, making it difficult to convert someone who strictly contributes to Ethereum projects to some other protocol, like Polkadot, for example. 

Based on my background I have seen a lot of referral programs, and their results tend to be quite binary: it either works really well, or not at all.

Why is this? It's because the people that spend their time working on your behalf, recruiting others to come into your ecosystem have to make a decision about opportunity cost. How much time and resources am I willing to commit to this? Also, the people who already have an audience have to put their reputation and social capital on the line by promoting you.

In a nutshell, the better the opportunity, the more they'll commit.

This means a few things have to be true:

**1. The potential rewards have to be really good**

![image](https://user-images.githubusercontent.com/40495037/152805756-5594d81c-4845-48e4-8d0b-d0d929faa7ff.png)

40% recurring revenue is an incredibly good offer, and I have watched plenty of people devote tens of hours per week to the Clickfunnels affiliate program. I believe they're either worth $1b or close to it, and a very large part of their customer base come from affiliates.

**2. Referrer has to be confident that their reward will be counted**

When the referrer has to trust that referee manually inputs them as the affiliate you know for sure that some of your rewards will not come through due to laziness, forgetting, or human error. Having an automated tracking system takes care of that.

**3. (Not required, but can help a lot) Referrals benefits both referrer and referee**

![image](https://user-images.githubusercontent.com/40495037/152805528-19ed5e52-0927-4206-af4a-2ec05e563945.png)

This removes any "ickiness" of sending referral links to your friends as it benefits both parties.

And.. if you want people to put in serious effort (researching opportunities, creating content in the form of SEO optimized blog posts, youtube videos, and so on) 

**4. They also have to believe that their efforts can be rewarded accordingly, meaning if there is a cap to their rewards it's a pretty large cap, or none at all.**

If there is a cap, like 5 invites per person for example, we could expect good results, but you would see less "evergreen" things like attempts to rank blog posts and youtube videos, as those would only be effective for a short while and therefor not worth the effort.

## How can solve it?

We allocate a larger JOY budget to the referral program (incentives have to be really good). Reward both the referrer and the referee (of course, upon verification).

We would need some type of conversion event.. for example.. 

- Referrer sends his invite link to a friend who is interested
- Friend gets taken to a sign up page where his email is captured, and the referral is stored (and if he doesnt sign up right there he is cookied and the friend signs up 12 days later, the referrer is still stored) - this would actually be done via Mailchimp where the referral would be a tag on the contact, which you can do what you want with after that with API
- OR they're taken to a page to create their on chain membership where the referral tag is stored
- Friend is taken to onboarding experience, and is initiated
- Etc etc

Then you could have some type of simple dashboard showing 3 figures:

- `Uncaptured rewards` (these are all the potential rewards that they have technically earned, but have not yet been unlocked due to the referees not becoming verified) This number may also motivate them to actually help the people they referred to become verified by continuing to be valuable to the project since they're incentivized to do so
- `Captured rewards` (rewards that they now qualify for since the referees have verified)
- `Amount released` / `paid out`

Once the referral program is in place, you share it with existing audience, obviously general awareness alone would come from people actually trying to promote the program to their social media followings, and you could run advertising campaigns to get further sign ups.

Now, what sort of effort and resources would we have to deploy to execute on this? How long would it take?

TBD

**Comment by bedeho** [comment]
I suggest we only do this after seeing how the basic referral system shakes out once incentives are launched at least.

**Comment by mrexpat** [comment]
One thing I just realized here is that if we just accomplish 2 things with the program, they could seriously move the needle for our referral program, and it will not require extra time, resources or anything.

### 1. Make it beneficial for both parties to be referred

If we do this, the automatic tracking becomes much less of a dealbreaker since it's now in the best interest of the person being referred to enter who referred them. I'm assuming the automatic tracking would really be the main bottleneck to doing what I discussed above as it would require planning, development, etc.

### 2. Make the rewards really really good

I can't claim 100% comprehension of how the referral rewards work at this point, because I find it quite confusing. Ben showed me the Airtable, but it wasn't really clear what was going on.

Why even bother having a fluctuating reward as opposed to a simple "You get $1,000 worth of $JOY if you refer a person that gets verified". No changing rewards or complexity, and very simple to understand.

The $1,000 is an example figure I'm not married to, but it is very good imo. Let's say because of the high number we ended up getting some 100 - 200 new high value contributors for effectively $100k - $200k worth of $JOY - that would be a great investment IMO.

This, along with other marketing activities I believe would have a very big impact.

**Comment by bedeho** [comment]
>   I can't claim 100% comprehension of how the referral rewards work at this point, because I find it quite confusing. Ben showed me the Airtable, but it wasn't really clear what was going on.
>
> Why even bother having a fluctuating reward as opposed to a simple "You get $1,000 worth of $JOY if you refer a person that gets verified". No changing rewards or complexity, and very simple to understand.

This is how it works, now, the Airtable is not a useful guide to understanding referrals, that would be the handbook.

https://joystream.gitbook.io/testnet-workspace/testnet/testnet-rewards#refer-a-friend

**Comment by mrexpat** [comment]
> > I can't claim 100% comprehension of how the referral rewards work at this point, because I find it quite confusing. Ben showed me the Airtable, but it wasn't really clear what was going on.
> > Why even bother having a fluctuating reward as opposed to a simple "You get $1,000 worth of $JOY if you refer a person that gets verified". No changing rewards or complexity, and very simple to understand.
> 
> This is how it works, now, the Airtable is not a useful guide to understanding referrals, that would be the handbook.
> 
> https://joystream.gitbook.io/testnet-workspace/testnet/testnet-rewards#refer-a-friend

Why have a limit? The beauty here is that if we get everything right we only pay for performance. If no referrals happens it costs us nothing, if we get a shitload of high value contributors who get verified we happily pay for it. The verification is enough to prevent sybil attacks.

I believe this kind of thing has a disproportionate negative impact on the program, because if people believe that there's a chance they go out there, put their reputation on the line by referring people, but other people grabbed the rewards before them, and they don't get rewarded, then they'll conclude that it's not even worth trying.

**Comment by mrexpat** [comment]
It'd be better to not have a limit, and give ourselves the option to shut down the program for whatever reason if need be. Then there wouldn't be this legitimate reason for people to attempt to refer others.

**Comment by bedeho** [comment]
> Why have a limit? The beauty here is that if we get everything right we only pay for performance. If no referrals happens it costs us nothing, if we get a shitload of high value contributors who get verified we happily pay for it. The verification is enough to prevent sybil attacks.

Because there is a fixed amount to give away, there is no sense in which we could give away an unconstrained number of fixed $JOY allocations, even if they were all non-sybill excellent people: the pie is actually fixed in so far as the size of each slice is fixed.

> It'd be better to not have a limit, and give ourselves the option to shut down the program for whatever reason if need be. Then there wouldn't be this legitimate reason for people to NOT attempt to refer others.

This does not solve the problem, unless you are basically saying to that we don't honor legitimate referrals ex-post. You should also be aware that referrals rewards are not fixed from one council period to the next, in the sense that this is no guaranteed. There is a value in keeping them stable or fixed, but its not clear that we will be able ot honor that, so anyone inviting people at time T cannot really claim that the recipient will receive Y perpetually, as the time at which people are seeing this message may be way later.

**Comment by mrexpat** [comment]
> Because there is a fixed amount to give away, there is no sense in which we could give away an unconstrained number of fixed $JOY allocations, even if they were all non-sybill excellent people: the pie is actually fixed in so far as the size of each slice is fixed. >

It is fine to have a fixed amount to give away, but the way we present it fundamentally changes the motivation for actually referring people.

Ask yourself: if you knew there was a chance you could go through the trouble of referring people and not get rewarded for it, would you do it? Especially given that you don't actually have any data on how likely it is that other people will scoop the rewards before you, making it impossible to calculate the risk/reward.

Instead, what you can do is keep the fixed amount to yourself, do not put a limit that provokes the thought pattern I outlined above, and once you hit the limit of how much you intended to give away, then you can simply suspend the program. Nobody gets screwed because everyone who did refer people beforehand gets rewarded, but we also don't shoot ourselves in the foot by giving them a huge reason not to refer people, by saying thanks for the referral, we may or may not reward you for it.

These things may seem small. They are not. It's literally what makes or breaks the efficacy of a referral program.

> This does not solve the problem, unless you are basically saying to that we don't honor legitimate referrals ex-post. You should also be aware that referrals rewards are not fixed from one council period to the next, in the sense that this is no guaranteed. There is a value in keeping them stable or fixed, but its not clear that we will be able ot honor that, so anyone inviting people at time T cannot really claim that the recipient will receive Y perpetually, as the time at which people are seeing this message may be way later. >

It solves one aspect of the problem which is the motivation fueling the decision of whether to refer people or not. I'm saying

- Do not make the rewards they earn a MAYBE. Give out the rewards, and if we hit our budget for referrals, shut down the program instead of spreading out the budget over time by putting an allowance for each council period.
- A fixed reward is not necessarily required, it would just simplify things slightly

The reason I'm all about the details here is because

a) I believe this can be an incredibly effective way for us to attract the right people
b) The way the program is designed at the moment will yield similar results as the last referral program, since

- We are saying you might get rewarded you might not
- Currently we have manual tracking, but as described above this can be resolved simply by offering benefits to BOTH parties, so this would need to be discussed as well
- Personally I'm still very unclear on what range the rewards are actually in, or what the total budget is for this

If we can..

- Avoid ANY mechanism that decreases motivation to refer people (such as the limit, or in the last referral program where each time someone was referred a small chunk of the referrer's rewards were actually given to the referee since they had a fixed 15% pool to earn from)
- Incentivize both parties to refer, and be referred
- Make those incentives really juicy (I'd much rather have crazy good incentives and spend the whole budget, than mediocre ones and nobody does anything to refer ppl)

Then this can be incredibly effective!

If we fail at ANY of those points, we should expect similar results to the last referral program, which I think would be a waste of an opportunity.

I understand there are some challenges you pointed out above, but nothing we can't flesh out.
