### ISSUE TITLE
coinmarketcap profile out of date

### ISSUE THREAD

**Issue by mochet** [Joystream/marketing#190]
I don't know who has access to adjust this, but there is some information that should be changed:
https://coinmarketcap.com/de/currencies/joystream/

The project is on almost 200 people's watchlists.

* Community link goes to old Twitter account which no longer exists
* Chat goes to Telegram, preferably should go to Discord
* Whitepaper link is broken (I don't think there is a whitepaper anymore)
* No link to website

**Comment by mrexpat** [comment]
Been in touch with them but haven't gotten around to getting access to the profile.. someone outside JSG has made it - here's the info on what to do https://docs.google.com/presentation/d/1p0-EjHE4ELpLZ8kwzP855L5x3uq941oUpCfIYSraa0g/edit#slide=id.g88e0475fa0_0_3

**Comment by mochet** [comment]
I guess this was sorted, so closing

**Comment by traumschule** [comment]
whitepaper link is still 404. [There](https://discord.com/channels/811216481340751934/813361923172335648/950446954612154368) was the idea of a lightpaper instead.

**Comment by mrexpat** [comment]
> whitepaper link is still 404. [There](https://discord.com/channels/811216481340751934/813361923172335648/950446954612154368) was the idea of a lightpaper instead.

we just got access to the profile yesterday, someone outside of jsg had made it. i removed this link today, but it has to be approved by CMC before publishing
