### ISSUE TITLE
Joystream doesn't have a vision, and desperately needs one

### ISSUE THREAD

**Issue by mrexpat** [Joystream/marketing#193]
## Background

Something I've been thinking about a lot lately is the importance of a company having a vision.

It's become clear to me that this is much more important in web3 where anyone can speculate / get a piece of the upside by investing and talking about the company.

If you reverse engineer the thinking process that the average person deploys when it comes to investing in a project, it all centers around the vision. It boils down to this:

_"If vision X comes true (or even partially true), what would that do to the coin price?"_

The answer to that question dictates their action. A good example is Cardano which has been known for having a very high market cap in relation to the actual use of the product.

The Cardano vision is literally the pinned tweet on the founder's twitter.

<img width="599" alt="Screenshot 2022-03-02 at 10 27 29" src="https://user-images.githubusercontent.com/40495037/156333688-6b2fe366-2c0a-4e5c-8ff2-b195157a3906.png">

A lot of Charles' live streams on youtube are longer form talks that all support this vision.

The result? 

Close to a $100bn market cap at its peak, with very little usage of the actual product (especially at that time).

The point here is that a solid vision can be instrumental in getting people to invest in the project, and also become evangelists that spread the word. At this phase of Joystream those evangelists would be very useful.

A great vision is a clear and concise statement that allows people to convince themselves to "buy in" to a project, both literally and psychologically.

Another great example is the Swedish state lottery ticket "Triss" - their tagline translates to "Suddenly it happens" as in.. suddenly you win the jackpot.

This is not a vision per se, but it accomplishes what a vision should accomplish, which is to get buy in through a clear and concise statement. If you are debating whether or not to buy a lottery ticket, and you tell yourself "suddenly it happens", you're buying a ticket.

## Joystream

The truth is, Joystream does not have a vision, at least not one that is clear and concise. I will not attempt to come up with one in this issue, but rather add some food for thought.

One challenge is perhaps that there may be a long term and a short term vision that may not be the same.

For instance, getting Atlas to succeed in getting youtube creators to come over and build a channel on Joystream warrants a different vision than attracting developers and entrepreneurs to build amazing video dapps on Joystream blockchain.

We should discuss, perhaps in the next marketing meeting, what the future demand is that we are building Joystream to fulfill so that people can read about Joystream and conclude that there's a strong likelihood that the need for Joystream will continue to grow as we get closer to this future.

For example.. do we think that decentralization is an inevitability (if so we should talk about why) and this means the need for a decentralized video platform is therefor going to increase as we approach this future world where the majority of apps are decentralized as opposed to the situation today where probably 99% are centralized..?

Or are we about the creator economy where creators can do their own thing and make a living off of that, and if those creators are helping some platform succeed, then they should be getting a part of the upside.. 

Etc..

If we accomplish this we will see more evangelists, and investors when that time comes.

**Comment by mochet** [comment]
So I have started working on one solution to this issue, but it is still in early development.
https://github.com/Joystream/marketing/issues/199
