### ISSUE TITLE
Suggestion: Move incentives v3 planning to Notion

### ISSUE THREAD

**Issue by mochet** [Joystream/marketing#195]
# Please provide positive/negative feedback!

@bedeho @bwhm @mrexpat @blrhc

I'm putting this here to make sure it can be read and hopefully considered ASAP so that it can have the most benefit if it is considered.
* If what is suggested might negatively impact people's current workflow then please say so
* Note: there are some integrations available between `Notion <> GitHub` so it may be possible to minimize disruption.
* The scope of this is only `incentives v3` launch--nothing to do with `olympia`.

### Countdown to blast-off!!!! 🚀
We're currently in the lead up to launching `incentives v3` and unless there is some organizational space/system I'm not aware of it is proving to be confusing and challenging to understand what the current state/progress of things is.

### We don't seem to have a map
* I think a map is critical for information sharing purposes--we should be building one up leading up to the launch of `Incentives v3`.
* It should be something anyone relevant can check at any time and understand the progress and the timeline of everything related.
* I can help to set it up and keep information updated (a secretary of sorts!) I can also help anyone who isn't super familiar with it and I can also help to transition any GitHub stuff if necessary.

### Notes
* `Incentives v3` from our community side will heavily revolve around Notion, so it may be time to start using it for this purpose? It seems like its going to be required to know how to use/understand it for everyone at some stage quite soon.
* The `marketing` repo is being used a lot for stuff already, but unfortunately I don't think its great for building a map.
* I've been developing my own organizational/work space on Notion so I am getting _really good_ at it 🤡 -- and it offers very clear advantages over GitHub (IMHO)
* There are actually several integrations available between `Notion <> GitHub` so it may be possible to achieve this some way that doesn't disrupt peopple's current workflow or require them to keep tabs on another platform that they usually don't.
* This sync tool seems like it would make it trivial to accomplish this: https://githubnotionsync.com/

(I know GitHub has a `Projects` tool for some level of organization but since this isn't used for this repo anymore I assume it isn't very good?)

**Comment by bedeho** [comment]
I largely did not understand the goal of this issue, in terms of problem or solution, but it seems related to this:

>  I'm not aware of it is proving to be confusing and challenging to understand what the current state/progress of things is.

This is highly highly unpredictable, and it comes down to some internal miscommunication failures we have had about the state of prior testing, which left very divergent expectations in the team about how ready Pioneer 2 was for launching. Hence, we are now in a high pace testing phase where new things are being discovered daily. There is no easy fix for this at this point, but we could communicate more actively around it, however, anything beyond the superficial "its at least 7-10 more days" would get too in the weeds for most people, and so it would get pretty repetitive after the 2nd or 3rd time.

**Comment by mochet** [comment]
> I largely did not understand the goal of this issue, in terms of problem or solution, but it seems related to this:
> 
> > I'm not aware of it is proving to be confusing and challenging to understand what the current state/progress of things is.
> 
> This is highly highly unpredictable, and it comes down to some internal miscommunication failures we have had about the state of prior testing, which left very divergent expectations in the team about how ready Pioneer 2 was for launching. Hence, we are now in a high pace testing phase where new things are being discovered daily. There is no easy fix for this at this point, but we could communicate more actively around it, however, anything beyond the superficial "its at least 7-10 more days" would get too in the weeds for most people, and so it would get pretty repetitive after the 2nd or 3rd time.

Thanks for the reply, it helps explain things a whole lot better for me. Basically answers what I was concerned about.

The purpose really is that `incentives v3` is dependent upon its own set of components which are completely independent of the coding (runtime/pioneer/atlas) side of things and I guess the type of work is a different style than what is present on GitHub. I was mainly concerned with `incv3` not being discussed much at all compared to the coding side and as I am involved in parts of it, I wanted to make sure communication was adequately flowing between us all about its status.

So while a move isn't strictly necessary, I may take it upon myself to work on this at least slowly in the background, and to make the status of aspects I deal with far clearer (although as you have said the current priority is different)

**Comment by bedeho** [comment]
> I was mainly concerned with incv3 not being discussed much at all compared to the coding side and as I am involved in parts of it, I wanted to make sure communication was adequately flowing between us all about its status.

Discussed by who with whom? I am not sure what more there is to say about incentives 3, or what we can do for people to understand it more clearly. I did a video on it on the community call, that could be repurposed perhaps. but the handbook is the most comprehensive explainer.

I think I still don't know what exactly you are asking for as a remedy.

**Comment by mochet** [comment]
> > I was mainly concerned with incv3 not being discussed much at all compared to the coding side and as I am involved in parts of it, I wanted to make sure communication was adequately flowing between us all about its status.
> 
> Discussed by who with whom? I am not sure what more there is to say about incentives 3, or what we can do for people to understand it more clearly. I did a video on it on the community call, that could be repurposed perhaps. but the handbook is the most comprehensive explainer.
> 
> I think I still don't know what exactly you are asking for as a remedy.

The update you provided gave me a much better understanding of current priorities and nothing is needed right now. The only reason I was confused is because I didn't quite appreciate the change of priorities until your response.

None of this refers to anything post-`incentives v3` launches, purely the lead up to that happening. Nothing involving community or people understanding it--just the building blocks that have to come together for it to launch and how they will all fit together.

**Comment by mochet** [comment]
This is no longer relevant, closing
