### ISSUE TITLE
List of Joystream "competitors"

### ISSUE THREAD

**Issue by mrexpat** [Joystream/marketing#204]
We're making a comparison table https://github.com/Joystream/marketing/issues/205 , post all video blockchain projects, and youtube alternatives here

- Odysee
- Theta
- Etc

**Comment by leetjoy** [comment]
Here is collected data by the WG
## VIDEO PLATFORMS
    theta
	lbry
	LivePeer
	odysee
	videocoin
	Mediachain
	BitChute
	d.tube
	dlive
	Verasity
	Steemit
	flixxo
	BitTube
	3speak
	Viewly
	Minds
	chainflix
	peertube
	AIOZ Tube
	MTonomy
	StoryFire
	Streamanity
	Cos.tv
	Flote
	Vevue
	Bottom Line
## OTHER (mostly audio)
    moltencloud
	molten
	thepopnetwork
	POP Network
	Pepo
	Civil
	Dot Blockchain Media
	Sapien
	muzika.network
	muzika
	artory
	Digimarc
	vezt-inc
	Open Music Initiative
	OPUS
	Musicoin Foundation
	Mycelia
	Viberate
	Blokur
	eMusic
	VOISE
	BitSong
	Audius
	OnChain Music

**Comment by mrexpat** [comment]
@josurz98 let's figure out the Top 5 that we can compare Joystream to.. let's make a list and confirm with Bedeho

**Comment by mrexpat** [comment]
Theta
LivePeer
Odysee
BitChute
Rumble
