### ISSUE TITLE
Creator cashout incentives in Ephesus

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#224]
# Background

Ephesus will introduce council paying creators and creators being able to receive this in Atlas in a new section of Atlas Studio.

# Proposal

We need to introduce something in the incentive scheme which

1. gives council a reason to pay for sensible useful content
1. gives creators a reason to upload sensible useful content

It seems the most straight forward way is just that we introduce a new component of the scoring system which measures publishing of new content and rewards the council correspondingly. Just like any other activity, such as bounties or referrals, the tokens cashed out by creators will draw from the council tJOY budget, and it should earn the creators a share of the $JOY budget. 

Obviously we need some constraints here to ensure that:

1. **Quality:** higher quality or more valuable content gives more points, and below a certain bar you get no credit. 
2. **Ownership:** it is somehow proved that for all content in this scheme, the true owner is the actual publisher, unless it is in the public domain.

I think the easiest way to operationalise these two is to just say

* Only content from YT or another major platform, where we provide a list, where we trust the view counts are eligible, and the content must already be published there.
* Owner of source account must publish a message from their external platform account to prove ownership.

## Payment of $JOY and $tJOY

A valid video is paid $JOY and $tJOY as follows. The council will choose to pay `X` amount of $tJOY to all videos in a given council period. By pay, we refer to how much money they able to cash out in total, not what is _actually cashed out_, as the latter depends on whether creators bother to do so. By _able to cash out_ we just mean the biggest number the council ever sets as payout, as the council can actually reduce it, but only in rare abusive cases. Suppose the total number of views across all videos submitted, at time of submission, is `Y`, and suppose this total for a particular channel is `C`. In this case, this particular channel receives `[C/Y] * [X/tJOY_BUDGET]` share of the overall `JOY_BUDGET`.

## Note

- We need a way to NOT pay non-verified publishers even though the council makes a mistakes and pays tJOY. Not really a question.
- The council must list and explain why explicitly it rejects certain creator videos.
- This scheme does not incentivise creation of Joystream original content, or measure views _on Joystream_, but it just seems like that is something we can consider later, as its just more work for what will be a lot less volume of submissions.

# Questions

1. What is good list of platforms.
2. How exactly do you publish a message on these platforms, should we make tutorials
3. How exactly do creators opt into this scheme and present their proof, also in a way that Jsgenesis can verify to score council.
4. Should paying non-verified publishers lead to punishment in scoring?
5. Some how it seems the content curators should be involved in doing some of the heavy lifting here, perhaps proposing the specific payout based on all the work and validation, and council accepts or rejects.
6. Perhaps there is a way we can encourage the content curators and council to do a bit of outreach to solicit and capture creators by having a scheme that pays more for stuff that has more views

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202134085481638) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
# Idea for how to get verified

Channels publishes a special kind of marketing video saying something like "claiming my joystream channel", possibly not listed so they don't need to disturb their audience?

**Comment by bedeho** [comment]
Absolutely, that is critical for performance!

**Comment by MindsGaming** [comment]
https://github.com/Joystream/marketing/issues/236

**Comment by eclipsingbinary** [comment]
Sorry it took me so long. I didn't really have any ideas

1. What is good list of platforms?

Wherever the content creator has a following as long as it can be verified.

2. How exactly do you publish a message on these platforms, should we make tutorials?

Publish their Atlas channel link in the other platform's profile at the moment of verification. It can be removed after.

3. How exactly do creators opt into this scheme and present their proof, also in a way that Jsgenesis can verify to score council. 

Via a content creator verification bounty 

4. Should paying non-verified publishers lead to punishment in scoring? 

Yes, unless made explicit that a certain creator should be paid.

5. Some how it seems the content curators should be involved in doing some of the heavy lifting here, perhaps proposing the specific payout based on all the work and validation, and council accepts or rejects.

Perhaps having a reporting form. Entering a link to a post where the creator is advertising a link to their own Atlas channel or video. Curators can verify these reported links.
