### ISSUE TITLE
Incentives 3.0

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#23]
> Third time is the charm

# What is this?

This is an attempt to just share a high level description focusing on conveying how a very wide range of changes will be made to our testnets, fm program, onboarding, processes. In the interest of time, many details have been left which are not of deep conceptual significance

# The Pitch: What are we getting here?

1. Break Jsgenesis financial constraints on participation by rewarding primarily with $JOY rather than $USD.
2. Make council solve realistic resource allocation problems, without detailed directives about how things should happen.
3. Increase conversion of arrivals into contributors by having systematic way into activities 24/7.
4. Reduce burden of grading fm submissions of varying quality and value.
5. Clear transparent signals to community about what activity has what level of value at any given time, and a clear record of why someone got tokens.
6. Better record of data upon Jsgenesis can base analysis and decisions for how to update the scheme.

# General

1. Everyone earns $tJOY + $JOY directly on testnet, FM points are no longer a thing.
2. The primary incentive for all activity is $JOY, while $tJOY is only to cover some subsistence costs needed for time & equipment.
3. There is a global $tJOY minting limit for each council period, from which all non-validator minting is drawn. (Pre-olympia, council will decide how this shuold be split across its own and WG mints by telling Jsgenesis what to set council mint to.)
4. Each testnet activity, like being a council member, storage worker, content curator, bounties, etc., has a dedicated $JOY budget for each council period from which people earn.
5. For all worker roles, with the exception of council members and leads, the % share of $tJOY they earn out of all $tJOY issued for that activity is equal to the share of the $JOY budget their earn for this same activity.
6. For bounties, they work as worker role, except that the actual $JOY earned is scaled by how well the contributor did, as measured by what % of the $tJOY budget or their bounty that they actually received. Keep in mind that the $JOY budget used as reference is the period during which the work is assigned, not delivered. Lastly, there is a cap on the $JOY to avoid situations where a very low number of bounties are assigned for arbitrary reasons.
7. As before, an amount of USD is added to the value backing $tJOY at the beginning of each period, and this value is called the _Jsgenesis subsidy_ or just _subsidy_.
8. For the council and lead roles, a network performance score is computed by Jsgenesis based on predefined public metrics. This score determines how much of the council $tJOY + $JOY budget the council and leads actually receives.

# Bounties

## In the future: READ THIS FIRST

> Note: The current bounty scheme is made purposefully as simple as possible, as the bounty module will likely be rolled out in Olympia, and this likely will have a substantial impact on what is the ideal process.

When the Olympia+bounty module goes live, $tJOY funding for bounties will be locked up when the bounties are created. The funding for the bounties will be out of the budget from the working group budget of the HR working group. Of course anyone can fund and create a bounty, but this is not relevant to the testnet incentive scheme directly per say. Workers in the working group can get smaller daily $tJOY slush funds for funding fresh bounties on demand, as users come in, and anything left over can be returned to the WG budget, as explained here https://github.com/Joystream/joystream/issues/2977. Bigger bounties can be funded by the lead by spending from the budget as needed.

Now, while on Giza we may not have this, so we will need to simulate this arrangement as closely as possible, that is described in the next section.

## Now: pre-Bounty module support

We don't have WG discretionary spending, refunds to wg budget or a bounty module. This means that whenever a new bounty, or a collection of bounties, are to be listed as available, the council must commit to this by doing a spending proposal to the lead of the HR group of the appropriate size to cover this. The lead must _not_ spend these funds for anything else before they are needed for this purpose, and if there is a change in leadership, the funds have to be transferred to the new lead. This is obviously not a great trust model, but its worth trying to stay close to the future scheme. The lead can parcel this out to the relevant workers on call to allow for authorising smaller bounties quickly as people come, in particular the _recurring bounties_ mentioned below. Funding for recurring bounties, since they in principle could have unlimited demand, is capped by the council to some limit per time period. Bounties will be managed in the coming CRM. The $JOY earned is determined as described in the section [#general] section above.

FIX

- All bounties will live in the new testnet CRM (see below).
- Bounties will be defined by
  - a budget in $tJOY
  - a description
  - a suggested man-hour count
  - a description of who should evaluate delivery, as distinct from manage, who is the one who ultimately
  - a possibly assigned worker who is working on the bounty.
  - a referene to where discussion happnes: Discussion between worker, manager and evaluator of a bounty will live on a dedicated forum thread setup when work starts.
- All bounties are managed by the HR working group, meaning they
  - assign who is working on it
  - make sure delivery occurs in a timely manner
  - make sure evaluation is done, if that is a third party
  - decide what final outcome is in terms of how much of budget should be paid out, or if p
- There are three types of bounties
  - **Normal Jsgenesis Bounties:** Authorised by Jsgenesis, but may originate from council, working group or anywhere else.
  - **Recurring Jsgenesis Bounties:**
    - Same authorisation as normal bounties.
    - Whenever some worker is assigned to work on this bounty, a new instance of it is automatically created by the HR group, so as to make the opportunity open to all.
    - There is a limit weekly cap to how much $tJOY and $JOY can be spent on assigned bounties of this kind. This is tracked in CRM.
  - **User Created Bounties:**
    - Is authorised by HR working group by input from users, in particular new users looking to make their own opportunities.
    - There is a limit weekly cap to how much $tJOY and $JOY can be spent on assigned bounties of this kind. This is tracked in CRM.
    - There is also an individual per bounty cap on the max amount of $tJOY and $JOY that can be budgeted.
- All varieties can be created on an ongoing basis.

# Founding Member Program

1. No manual evaluation of each persons contribution per period is needed, hence no scoring period submission is needed. Only the final decisions about granting status is evaluated manually.
2. Any tokens earned are only withdraw-able once you reach founding member status, before this time, any tokens earned are effectively still just a promise of an allocation. This is however still different from the old point system, because the quantity is locked in.
3. People with current FM points will be converted into token allocations.
4. Anyone earning tokens, starting from 0, will be capped at some low number x > 0 until they go through a Jsgenesis KYC process, this is called getting _verified_. Any tokens earned in the time the cap x is reached, but KYC has not been completed, are permanently lost. The value x should be roughly equivalent to 1 full council period of participation for the least important role. During this process, the user most also provide a serious avatar and a 1-2 line description on their membership profile, with reverse lookup information. During KYC, the referring member is also noted, this is the last moment such data can be provided.
5. Everyone can still earn tokens for referring new people to the community. Specifically, there is a separate referral pool of $JOY for each council period, and any member verified in that period corresponds to a fixed amount of $JOY out of this pool, and if pool is exhausted, everyone takes a proportional haircut.
6. Anyone will get a share of the referral pool equal to the $JOY earned at the end of a council period by members who they referred who are verified as a share of all $JOY earned by everyone verified.

# Onboarding

1. Council size will be reduced to 5 people, and council period will be 2 weeks, and Jsgenesis will use its considerable $tJOY share to make sure, through elections, that new promising candidates get to try working on the council.
2. Working groups will be induced, through the network performance scoring, to perpetually make room for newcomers in worker roles in each council period and to have a perpetually open opening to which people can apply. Same for lead roles if needed, but less frequently.
3. There is a new dedicated operations group, called the _human resources working group_, which will be focused on
    - 24/7 greeting new website onboarding experience users in live-chat, inducing them to join Discord.
    - 24/7 greeting new Discord entrants and helping them get setup with a membership, a bounty and on their way to a role.
    - managing bounties, that is helping with creation and evaluation of outcome and payment from Jsgenesis
    - re-engage members at all stages of membership lifecycle from starter to founding member and beyond.
5. There will be a new dedicated operations group, called the _marketing group working group_, which will among other things be focused on sourcing fresh quality members for our onboarding flow.

# Reporting

 1. Each working group will be induced to submit a report at the beginning of a council period to the council in public, called a _working group period proposal plan_, which outlines
    - Current group composition.
    - Planned hirings, emphasizing newcomers.
    - Planned firings.
    - Onboarding plans for newcomers.
    - Ranked list of suggestions for problems groups should attempt to tackle, and how, with corresponding budgeting, marketing or other resources needed from council or Jsgenesis.
2. The council will be induced to submit a report at the beginning of a council period, called a _period plan_. This plan should be based on the plans from the prior period and the working group period proposal plans. It should outline
    - Prioritization to each working group about what they should focus on solving.
    - How total $tJOY budget will be allocated across groups and council.
3. Each working group will be induced to submit a report at the end of a council period to the council in public, called a _working group period summary_, which outlines
    - Accounting of how much was spent on what.
    - Actual hirings done.
    - Actual firings done.
    - Proposals for bounties that newcomers can tackle.
    - Changes made to the corresponding knowledge base (see below).
    - A summary on how well the working group performed on solving the described problem, and why.
    - Recommendations for what should be focused on in next council period in order to make group more effective.
    - Suggested changes to the purpose or practices built in to this working group, other working groups, the council or Jsgenesis' role, in order to increase overall effectiveness of the group or the project.
4. The council will be induced to submit a report at the end of a council period, called a _council period summary_, which outlines
    - Accounting of how much was spent on what.
    - Actual hirings done.
    - Actual firings done.
    - Proposals for bounties that newcomers can tackle.
    - Changes made to the corresponding knowledge base (see below).
    - A summary on how well the network as a whole performed, and what problems occurred.
    - Recommendations for what should be focused on in next council period in order to make the network more effective.

Key data from each report will also be added to the CRM by the lead or council.

# Information

1. The council and each WG will operate its own dedicated Notion space - called a knowledge base, owned by Jsgenesis, and will be induced to use it as a free space to develop its own routines for onboarding workers, training, documentation, etc. Jsgenesis will own the spaces in order to secure transfer of ownership between leads.
2. There will be a new Jsgenesis operated CRM (powered by AirTable), which will be a unified data warehouse for all testnet related activities orhestrated by Jsgenesis, covering FM activity, status, allocations, memberships, bounties, payouts, etc. It will have public APIs which will allow website & third-party community products to hook into information, and it will have UI forms and dashboards (powered by [AirTable Interfaces](https://www.airtable.com/product/interface-designer) ) that allow key network roles to write to the system.
3. A new Jsgenesis operated testnet community handbook will be introduced which replaces the role of the helpdesk, FM repo, and many uses of Joystream blog.

# Joystrem.org Onboarding

A new onboarding experience is being built to convert newcomers into FM candidates, based on the available activity on the pre-Olympia testnets, the following personaes make sense, showing a tailered subset of opportunities for each.

|Personae|Skills|Activities|
|---------|-----------------------------|-------|
| Builder | Software development, DevOps, Scripting, Product Design, Product Management, Product & User Research | Builder WG, Existing Bounties, Make your own bounty  |
| Techie | Server Administration, Infrastructure Engineering, SRE | Storage WG, Distributor WG, Validator, Existing Bounties, Make your own bounty  |
| Organiser | Planning, Management, Analysis, Writing, Persuasion, Debate, Collaboration, Communication | Council, Human Resources, Existing Bounties, Make your own bounty  |
| Marketer | Marketing, Content creation, Social Media, Crypto expert | Marketing WG, Content creator, Existing Bounties, Make your own bounty  |
| Curator |  Research, Collecting, Arbitration, Writing, Conflict Management | Content Curator, (Forum Moderator),Existing Bounties, Make your own bounty  |

1. There will be a 24/7 operated live chat which the human resources working group will run to service people in this epxerince before they enter Discord.
2. Real compensation, denominated in USD, for recent activities suitable for the role should be shown. The CRM will have USD denonminated value of activity of each type, which captures both $tJOY and $JOY value, and both should be emphasised, where the latter will be _large_.

# Jsgenesis Processes

Here are some ideas on what sort of process we need internally in Jsgenesis to manage this, but substantial detail is lacking at this time, and its not clear who needs to be in what meeting and what needs to be prepared in advance.

## Council Period Prep Meeting

As early as possible in a new council period there needs to be a Jsgenesis meeting (but should possibly be open to everyone) where one
 - Review insights from activity on forum, proposal discussion and onboarding process.
 - Review notes from reports in last period.
 - Review calculated network score from the last period.
 - Review proposal for feedback to provide about last periods results.
 - Determines who should be backed for next council.
 - Updates all $JOY and $tJOY budgets.
 - Determines bounties to sign off on.
 - Evaluates need to rotate out leads or wg workers more aggressively by adjustign metrics.
 - Determines new metrics for the upcoming period.

# Weekly FM Meeting

- Review basic metrics for how the program is doing and has done recently
- Review detiled metrics for specific leading FM status candidates.
- Make decision about whom to grant status to.

# Questions

1. Should we add slow decay dynamic to token allocation to
    - penalise people who just do the same thing for very very long, but hav every little value
    - encourage continued particpation from people after FM status
2. What is min size of council? what is max size?

**Comment by blrhc** [comment]
There seems to be a significant consideration not covered here (unless I've misunderstood the idea):
Is there some tJOY redistribution happening here?
Or will people with tJOY tokens in the current network have quite a lot of leverage and power within this new system, with the ability to compound the benefits they have already accumulated and secure very large JOY allocations for themselves on top of what they've already earned.

How does your proposed system make it easy for new people to get in and compete on a "level playing field" with the current community?

I feel like I'm missing something?

**Comment by bedeho** [comment]
> Or will people with tJOY tokens in the current network have quite a lot of leverage and power within this new system, with the ability to compound the benefits they have already accumulated and secure very large JOY allocations for themselves on top of what they've already earned.

The advantage of holding tJOY is as low as it has ever been as Jsgenesis will be inducing wg worker rotation, as stated above

_Working groups will be induced, through the network performance scoring, to perpetually make room for newcomers in worker roles in each council period and to have a perpetually open opening to which people can apply. Same for lead roles if needed, but less frequently._

as well as lead rotation and council newcomers being given slots by Jsgenesis as you stated. Also rewards to validation will go down a lot, which before was purely tJOY stake based.

> How does your proposed system make it easy for new people to get in and compete on a "level playing field" with the current community?

In quite a few ways, reread onboarding and bounties.

> I feel like I'm missing something?

Let's cover in a meeting then.

**Comment by bedeho** [comment]
The proposed transition so far has been

- Tell everyone to report their score by x weeks.
- Give everyone pro-rata share of x % (10 is most recent number) $JOY, regardless of FM status or not.
- Add decays in new system for all non-FM $JOY

**Comment by bedeho** [comment]
# Radical simplification

Fixed $JOY allocation for all role types and bounties up front, none of this uncertainty and complexity of what gives you what. Will be very nice in its simplicity, and penalty is low assuming diversity of contributions within each category is low. I think this is true.

**Comment by bedeho** [comment]
# Radical simplification v2

Jsgenesis provides total $JOY and $tJOY budget, and then this implies an exchange rate between the two, and every activity, so all $tJOY payouts, like salaries, bounties started, validation, etc., just correspond to $JOY implied by that rate, except council (which also has network score weighted payoff, imposing a cost of low relative spending of $tJOY, and thus $JOY, on other areas in the network).

**Comment by mmsaw** [comment]
I didn't get it all the way either: 
The tJOY in the future network remains a tool by which votes, payouts, etc.?
That is, for the performance of the bounty participant receives tJOY (conditionally liquid asset with which he can participate in the management of the platform, or get BCH) + $JOY which must be accumulated in order to qualify for FM status?

Or tJOY will remain only a story about money which can be exchanged into BCH, while the management tool will be $JOY now?

Translated with www.DeepL.com/Translator (free version)

**Comment by mmsaw** [comment]
Regarding questions:
1. 
- Penalties for people who do the same thing: it seems to me yes, it should be done, because many simply abusive system and earn some money, for example, simply pouring content into the Atlas, give for this $ JOY can be once, because in terms of FM - a person who in the future will manage the project - it is not valuable, because it does not contribute to the study project.
- Encouragement of FM for activity after the status: here the situation is ambiguous, on the one hand FMs at the expense of experience can take away a large share of work from newcomers, respectively, not allowing them to prove themselves. So imho FMs should move in parallel and show interest in the project differently from other participants, I can't say yet how exactly... it's just a conceptual vision.
2. My opinion - 10 board members is optimal, 5 is probably not enough.

**Comment by bedeho** [comment]
> That is, for the performance of the bounty participant receives tJOY (conditionally liquid asset with which he can participate in the management of the platform, or get BCH) + $JOY which must be accumulated in order to qualify for FM status?

Correct, but what we are going to do is that how much $tJOY you earn is part of determining how much $JOY your earn in a given period.

> Penalties for people who do the same thing

We are really trying to penalise people who _stop_ doing something, so they leave, before becoming FMs, so their $JOY allocation is diluted before its locked in.

> My opinion - 10 board members is optimal, 5 is probably not enough.

Noted, we are still debating this, last number we considered was 7, based on input from some FMs.

**Comment by mochet** [comment]
I have noticed some level of confusion regarding the current description of things (tJOY and JOY).

One way to alleviate this may be by adopting three terms:
- `tJOY` (testnet-only tokens that are exchangeable for BCH via JSG, have no bearing on anything else, these are for paying participants instant rewards, so they can be paid for work they're doing or for renting servers)
- `vJOY` (virtual joy. these are "virtual" mainnet tokens, none of them exist until a user has been accepted as an FM)
- `fmJOY` (FM joy. These are mainnet tokens currently rewarded to approved Founding Members, these will be mainnet tokens upon the network's launch)

The main benefit with this distinction is that users who have `vJOY` can easily be told what the description of `vJOY` is--"virtual" mainnet allocation that will not happen unless they are actually inducted.

The current system only has `JOY` for both `vJOY` and `fmJOY`. This is problematic in that is requires a bit of explanation (which I can imagine will have to repeatedly happen) showing that the tokens are for a non-FM participant.

(If there is some way this is already being addressed, it can be ignored)

**Comment by mochet** [comment]
@bedeho 
> The council and each WG will operate its own dedicated Notion space - called a knowledge base, owned by Jsgenesis, and will be induced to use it as a free space to develop its own routines for onboarding workers, training, documentation, etc. Jsgenesis will own the spaces in order to secure transfer of ownership between leads.

Shared Notion spaces require the owner to pay a fee for each user. This would introduce a fair amount of complexity to things and maybe make it a bit more difficult to continue using Notion for `post-mainnet`.

We are currently investigating alternatives, and if there is a web3 one it seems better to use that rather than Notion.
There is also an open source alternative that perhaps the `Operations Alpha` group could host.

**Comment by bedeho** [comment]
I agree with all of this, but since

- Jsgenesis is a natural steward now
- the cost is negligible
- Notion is phenomenally well crafted, and will make collaboration very efficient

I think starting with it is fine, but doing research for alternatives, experimenting, is also great.
