### ISSUE TITLE
Draft Website Redesign Plan

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#259]
# Document
This is a draft, based on feedback and review that occurs in this issue, a new final issue will be created.

# Background
The current landing page has this structure

* Menu
  * Content => Atlas
  * DAO => Pioneer
  * Team (Jsgensis)
  * Community => Discord
  * Lean More => handbook
  * Start earning => Onboarding flow
* Header
* metrics
* capture into onboarding flow
* available activities
* FM section
* manifesto
* "apps"
* road to mainnet
* Investors
* Footer
  * blog => Link
  * manifesto => standalone page
  * token => standalone tJOY page
  * Hydra => standalone page
  * Brand guidelinse => standalone page
  * We are hiring => Link jsgenesis site
  * Social Links: GH, Twitter, Discord

It largely reflects our focus on operating testnets and associated activities. By late Aug we expect to launch the Joystream main network. This is an important milestone for the project, transitioning from a prolonged testnet period. With this milestone, there many thing will change

1. There will be a shift in what you can do on the platform: Testnet games and founding member program will go away, tJOY & cashouts go away, and we will focus more on new initiatives for creatives.
1. There will be a shift in what guarantees the system provides: Critical state like balances, content, comments & reactions, NFTs, forum, proposals and everything else, enters a state of much greater permanence, if not immutability.
1. The native asset $JOY becomes value bearing.
1. There will over time be an increasing number of third party online resources and sites devoted to the project, and the main website is less canonical.

# Project: Process & Constraints
The main objective of this design project is to get a bare bones version of the website in synch with the state of affairs expected on mainnet launch, and then in subsequent stages developer further enhancements. I'd like us to take the following approach

* Very high frequency of iteration and feedback, ideally more than once per week.
* Use low fi mockups extensively, in particular in the beginning.
* Use the same brand identity as before, however only sparingly use our existing portfolio of illustrations, as they are of very mixed level of quality.
* Design execution and deployment in stages with limited scope.

# Target Audience
A significant challenge for us, both now and in the future, is that we are building a multi-stakeholder system targeting

* creators
* consumers
* infrastructure operators: validators, storage providers and bandwidth providers
* developers
* workers (curators, council members, bounty hunters, etc

This poses a challenge in terms of communication, because each audience has their own set of objectives and background knowledge. We are not unique in this respect, this is the case for a many protocols, so I decided to do a short review of the landing page of a handful of reputable project that are both on mainnet, and are known to have relatively good communication and design:

* [Radicle](https://radicle.xyz/): Very focused on speaking to main audience of developers only.
* [The Graph](https://thegraph.com/en/): Mostly focused on giving overall overview of project, but gives primacy to its primary audience - developers, but then has off-ramps for other specific roles in a dedicated section.
* [Filecoin](https://filecoin.io/): Here the main page is focused on a singular explainer of the overall system mission and function, and then there are separate pages for major categories: store, provide, build
* [Aragon](https://aragon.org): Mostly seems to have made their main page about the next version of their system, assuming a great deal of knowledge about what they are on behalf of the user, and then puts all specific paths for other audiences in various menu paths.
* [Arweave](https://www.arweave.org/): Entire experience is solely about very high level explainer of the project, totally separate pages for different audiences.
* [MakerDAO](https://makerdao.com/en/): Extremely brief overview, then it sends people off to separate places depending on whether they are interested in governance or using Dai, or something else.
* [Polkadot](https://polkadot.network/): Gives a high level overview of what function the network serves, primarily as relevant to developers, then sends people into different parts of the site, which frankly is gigantic and very hard to understand.
* [Audious](https://audius.co/): Very unfocused, its hard to see what they want to achieve with the page.
* [Livepeer](https://livepeer.org/): Splits between two agendas, give specific audiences a way to go down specific paths, and then also sending people for a general overview into their primer.

My takeaway from this is that while you may have many parts of your audience, you are best served trying to focus on the most important one for the project for whatever stage it is at, and then give secondary space in your website for other audiences that can be discovered with a bit more effort. In our case, certainly the primary audience we want to attract in this next stage are _content creators_, hence I think it may be useful to focus on them. This is not only because building the creator pool has is the most high value stakeholder to build at this stage, as it builds the content pool and means some of our very differentiated offerings can get used and explored, but also because the story we tell creators is a plain language one that can be understood by pretty much every other stakeholder in their pursuit to understand what we are doing, this is less so with some of the other roles.

## Separating Atlas
I think that since we are going to communicate more actively with creators, both on our website and in other venues and communications, it's time to distinguish the Atlas experience from the main Joystream platform. This will help with our communication with them, and the community, and opens up space for third parties to start running their own apps. Here is the issue explaining that

https://github.com/Joystream/atlas/issues/2512

**I think we seriously should consider giving it a standalone name and unique URL**. For the purposes of this document, I will refer to this name as _[Atlas]_

#### Atlas
https://github.com/Joystream/atlas/issues/2512

#### Website
Update as follows

* Menu
  * [Atlas]: links to new URL
  * Governance: links to Pioneer
  * Discord: links to Discord
  * YouTube Partner Program: link to new page
* Landing page: see below.
* About page: update people, add FMs, add investors
* Footer
  * Update token link (in footer) to link to handbook: https://joystream.gitbook.io/testnet-workspace/usdjoy
  * New FAQ link (in footer) that links to handbook:
  * New founding Members program link (in footer) that links to handbook: https://joystream.gitbook.io/testnet-workspace/testnet/founding-member-program
  * Remove: Tokenomics, We are hiring, "Repository"
* Remove:
  * Onboarding pages: https://www.joystream.org/start-here/what-is-joystream

**Landing Page**

**I am very open to alternative ideas, but this is my best suggestion for how to make this page effective.**

The goal here should be to speak as directly as possible to creators, conveying to them that Joystream is a new kind of service they should dare to take a bet on, that there are specific opportunities open to them now, and that these are attractive and will keep getting better. The real obstacle here is how to speak directly to creators, but also not totally loose out on other more crypto native audience members who also are interested in getting involved.

The main obstacle we will face in converting them is worth their time in terms of cost vs. benefits, so we must:

* explain clearly exactly what we are asking them to do.
* giving clear and credible indications about effort involved.
* giving clear and credible information about reliability and magnitude of payoffs.
* showing social proof that others are doing this: last x creators to sign up, features videos? featured creators? recent uploads? recent NFT sales? ...

Here are some of the benefits we can emphasise

* get $JOY: own part of new platform
* get free backup YT cannot take down: when yt-synch is up!
* monetise your videos with NFT sales and royalties: see a video?
* monetise your channel with a creator token: see a video?
* receive payouts from the DAO.
* make your community a stakeholder: promote and work with you.
* developers will build new apps for your content to reach new audiences.

Convey that some things are upcoming, not presently live, so people do not feel misled.
Certainly emphasising the new YPP, with a very prominent explainer of steps involved and CTA, makes sense.

### Stage B
* Real standalone token page with explainer (purpose, tokenomics, where-to-buy) and metrics like: prices, market cap, circulating supply
* New primer page.

### Stage C
* Real standalone FAQ page.
* Real opportunities page.

# Design Inspiration
I also wanted to share some subjective design inspiration that I feel should be considered. Rather than explaining all sorts of concepts and ideas with large bodies of vague texts and opaque visuals, which is quite common, we can instead leverage the fact that we have very high quality designs for product interactions that directly embody lots of the opportunities we want to convey. Here is a collection of other sites I have come across where I feel they do a very good job of doing this. They use a mix of both actually and conceptualised product visuals, sometimes with animations as well, to demonstrate the feature level value the reader may find very compelling. This helps both to signal that we have lots of working product features people can try now in an engaging way.

https://syndicate.io/clubs
https://ghost.org/features/
https://copilot.github.com/
https://scale.com/
https://github.com/features/issues
https://www.mightyapp.com/
https://radicle.xyz/
https://squads.so/index.html
https://talisman.xyz/
https://github.com/features/codespaces

# Next Steps
* Feedback from key stakeholders.
  * Community
  * Atlas: Adam, Klaudiusz & Dima
  * Marketing: Robert
* Update scope and approach.
* Create explicit timeline for delivery.
* Create new issue for finalized plan.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202543606101578) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@bedeho, thank you for the fantastic brief. It helps a lot in putting things in perspective and seeing the bigger picture behind what we're about to face in the first stage. 

Most of the questions I would have normally asked have already been answered (like the audience, outline of the content, or visual direction), so, as agreed with @dmtrjsg, I'll just dive right into stage A of the proposal and prepare more targeted questions for our next meeting. We're planning to discuss the first low-fi sketches of the landing page and potential attack plans for the Atlas branding.

**Comment by bedeho** [comment]
Sweet! very excited!

**Comment by bedeho** [comment]
> If this is true, shouldn't this creator-based website basically be the "About" page in the new, stand alone Atlas?

If a creator is already engaging with [Atlas], then do we need to spend time explaining lots of Joystream platform features? I do however think it makes sense for them to understand the place of [Atlas] in the broader Joystream platform in some sort of About page, epxlaining what this product is, and then linking back to the main project site. 

I do see your point that if Atlas stands on its own, when will creators ever actually want or need to visit the project website? What would make that happen? If it doesn't, then we are loosing something by focusing so very strongly on them, evne though I think the message to them has some general appeal that can work for other stakeholders also.

> And shouldn't the Joystream website be more of an overview, and "choose your own adventure" (consumer, developer, investor, creator) of the Joystream ecosystem?

Perhaps we could, but I don't think we have time to do that well. If we do that later, creators should be one of the paths, and so what we do now would not be wasted work.

>  I think the longer we keep mixing Atlas and Joystream the deeper that confusion will grow, and the more work it'll be to untangle it? If the Joystream main website is really an Atlas landing/about page, it'll just add to this confusion?

I am not convinced people are actually _confused_, but yeah, we are def. leaving something on the table if our message does not align with the actual distribution of audience members in the future.

**Comment by kdembler** [comment]
Looks sweet! Can't wait to discuss further

**Comment by dmtrjsg** [comment]
Adding ypp label to filter it in to the zenhub board
