### ISSUE TITLE
Cookies GDPR banner for joystream.org

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#277]
## Scope
Cookies GDPR banner for joystream.org

**Comment by toiletgranny** [comment]
@bedeho, @dmtrjsg How about this one? It slides up from the bottom, is way smaller than the current one, and it slides back in once you accept it.

https://user-images.githubusercontent.com/35307309/183440196-d7e91c9c-63df-45fa-acd8-caceaf6d0bc8.mp4

Figma prototype: https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=5523%3A129021&node-id=6363%3A299393&viewport=-11480%2C257%2C0.41&scaling=scale-down&starting-point-node-id=6363%3A284391

Designs: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=6363%3A284375

**Comment by toiletgranny** [comment]
@dmtrjsg Fyi, I don't have access to this ZenHub workspace, so I'd kindly ask you to move this issue into another column once approved. 🙏

**Comment by bedeho** [comment]
1M times better!
