### ISSUE TITLE
New landing page finalization

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#279]
- [ ]  #277 
- [ ] Remove mainnet top banner.
- [ ] Make subject in main page tagline have the following cycle: creators -> builders -> users
- [ ] Proposed set of changes to copy: https://github.com/Joystream/marketing/issues/280
- [ ] Fix vertical margin between quote section and NFT section.
- [ ] Fix corner artefact on Pioneer screenshot. Should be transparent or on top of background same as on landing page, looks bad now.

**Comment by dmtrjsg** [comment]
@toiletgranny preview branch to check margins > https://joystream-org-git-fork-dzhidex-new-landing-page-joystream.vercel.app/ and address relevant points from description

**Comment by dmtrjsg** [comment]
adding YPP label so its filtered into the joint board built on top of this label

**Comment by toiletgranny** [comment]
Ok, so I've been asked to review the implementation after the initial round of feedback that I left on Friday [in this issue](https://github.com/Joystream/joystream-org/pull/527#issuecomment-1206172259).

> In regards to the animations, I really like where we are at right now!
> 1. I noticed we're using some sort of limit, after which the parallax effect is no longer working. I understand the intention here was to have the visuals look 1:1 in our mockups at some point, but I wonder if we could drop this limit entirely. Or perhaps, if we need to keep it, increase the intensity of the parallax. Happy to discuss this over a quick Slack call, I know it's much easier this way with these things!
> 2. Now that we haven't implemented the interactive glass effect, I wonder if there's an easy way to compensate for the lost interactivity, and I thought of using some simple entry CSS animations. For example, with this [AOS - Animate on scroll library](http://michalsnik.github.io/aos/) by Michał Sajnóg, which is incredibly easy to set up and customize. Let me know if you think that's feasible. Again, happy to discuss on Slack!

1. While the current implementation is much better, I feel it could still use some tweaking, as some parts of visuals seem to pause their movement around the middle of the viewport, only to resume it when exiting the screen. How about another call to discuss this?
2. ✅ ❤️

> 1. Seems like we don't have `@2x` versions of images, which makes them blurry on retina displays. If image size was the concern, perhaps we could try out converting them to webp? Happy to talk this through on Slack and support in exporting the right assets from Figma.
> 2. Distance between the "Built on Joystream blockchain and managed by the DAO community." and the button is set to `66px`, should be `48px`.
> 3. The bottom padding in the hero section is currently set to `92px`, should be `96px`, just like the top padding.
> 4. For accessibility reasons, I don't think we can have `<h3>` tags above the `<h2>` ones. Would that be possible to keep all blue titles as H2s and the larger headings below them as regular `<p>` or `<span>` tags?
> 7. Margin between text and illustration columns doesn't seem consistent across different sections. For example, in the Payouts section, it's `34px`, while in the Video NFTs section it's `30px`. `30px` is the gap between columns in the grid that's been used for Joystream.org historically, so I believe it's best to keep it at this value. It's a minor thing, but if there's an easy thing to fix it all, that would be great. 
> 8. Margin between the four features in the Creator Tokens section is set to `96px`, should be `64px`.
> 9. On mobile, the margin between heading and the body copy, in text these slightly smaller columns for Creator Tokens features, is set to `16px`, but it should be `8px`. [(Figma reference)](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5989%3A325645)
> 10. Both vertical and horizontal padding seems to be off on mobile in the Manifesto section. Can we have another look at it? [(Figma reference)](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5989%3A318489)
> 11. Seems like we missed adjusting vertical padding in the rewardable activities section. It's set to `150px`, but it should be `96px`, just like in other sections.
> 12. On mobile, in the rewardable activities section, the margin between the body copy and the grid of boxes with activities is set to `30px`. Should be `64px`.
> 13. The text column in the Joystream DAO section doesn't seem to be centered vertically, just like all other text columns placed next to a taller illustration.
> 14. Vertical padding in the Jsgenesis section is currently set to `125px`, it should be `128px`.
> 15. Vertical padding in the footer should, ideally, be set the same way as in all other sections, meaning `96px` for both top & bottom. Currently it's `120px` for the top and `100px` for the bottom.
> 16. The margin between the "Stay up to date", "Investors", and the links parts of the footer should be set to `96px`. Currently, it's a bit different for each part. 
> 8. Similar to the Manifesto section, both vertical and horizontal padding seems to be off on mobile in the footer. Can we have another look at it? [(Figma reference)](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5965%3A280927)
> 17. Height of the navbar is currently set to `90px`. If we need to specify a fixed value, it should be `80px`, but — ideally — its height is driven by the contents inside and `16px` of top and bottom padding. 


1. ❌ Not fully addressed, some images (hero ones, for example) are not replaced with `@2x` 
2. ✅
3. ✅
4. ✅ (Would it make sense to have the uppercase titles placed in `<span>` rather than `<div>` elements?)
5. ❌ Almost there! The last thing to do is to remove the `left: -10px` from the Claim payout dialog illustration.
6. ✅
7. ✅
8. ❌ Not addressed,
9. ✅
10. ✅
11. ✅
12. ✅
13. ✅
14. ✅
15. ✅
16. ✅

**Comment by dmtrjsg** [comment]
@kdembler can I add these points here?

1. Hide the YPP section
![image](https://user-images.githubusercontent.com/93924525/183616859-3469237f-cc6b-4d26-96c7-c0617ac725c4.png)

2. Add "Sign up for Beta" on Creator Tokens Section poitning to this form > https://docs.google.com/forms/d/e/1FAIpQLSdjJpO1--qy3cK9-dVYDC14aTcaEmaqOzBJ7sdpbeufU4ydsg/viewform

[Figma >](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5965%3A280699)

Preview:
<img width="410" alt="Screenshot 2022-08-09 at 10 47 02" src="https://user-images.githubusercontent.com/93924525/183618845-a9cecf26-19d8-41f8-92b4-e7b1815f6c40.png">

**Comment by toiletgranny** [comment]
@kdembler the link to the Google Form should be this: https://forms.gle/soSRzZHq6Pg1yxG2A

**Comment by kdembler** [comment]
@dmtrjsg

1. It's hidden already
2. Added to the PR
