### ISSUE TITLE
Updated new landing page copy

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#280]
- `The streaming platform with more power to` => `The streaming platform empowering`
- `Built on Joystream blockchain and managed by the DAO community.`=> `Built on and operated by the Joystream blockchain and DAO.` 
- `Receive payouts for uploading quality videos` => `Rewards for publishing your videos`.
- `Upload high quality videos to get cash rewards from the Joystream DAO council on a regular basis. Popular creators are rewarded higher.` => `Publish your videos to get cash rewards from the Joystream DAO council on a regular basis. More popular videos receive greater rewards.`
- `Monetise your videos with NFT sales and royalties` => `Monetise your videos as NFTs and royalties`
- `New ways to engage and get support from your audience` => `Make your community a stakeholder in your future`
- `Put your token sale on autopilot or sell it on your own terms` => `Sell on your terms`
- `Receive stable stream of tokens every year` => `A weekly stream of revenue to support your work`
- `Flexible vesting schedule allows you to specify at what rate the newly purchased tokens should be unlocked. Paired with ability to run whitelist-only sales, it provides everything you need to feel safe about your investments.` => `Whitelisting allows you to control who can get access, and with vesting schedules for yourself and others you can make everyone aligned and focused on the future.`
- `Invest in other creators to receive a portion of their revenue` => `Scout for future stars and back your favorite creator`
- `We call for an arrangement where media platforms are accountable to the people they impact.` => `Due to network effects, economies of scale, regulations and political interests, we are today left with handful of massive institutions`
- ` Explore rewardable activities` => `Help build the future with us`
- `Our Investors` => `Investors`

**Comment by dmtrjsg** [comment]
@toiletgranny perhaps easiest to do is to upd in designs, and handover to Klaudiusz for implementation.

**Comment by bedeho** [comment]
This issue is just about copy, or is your point that you want @toiletgranny to reconsider breakpoints in titles and font sizes?

**Comment by dmtrjsg** [comment]
Makes sense tbf, I guess we could go with find and replace and then visually ascertain all still looks great :)

**Comment by dmtrjsg** [comment]
✅  All g there few points to address:

1️⃣  overlap of image in one section
@kdembler

<img width="460" alt="Screenshot 2022-08-08 at 18 38 13" src="https://user-images.githubusercontent.com/93924525/183479678-a770cba5-c4af-4cd0-b0af-8f7297c8bc82.png">

2️⃣ 
Do we need to specify the podcast Episode number here? 
@bedeho 
<img width="293" alt="Screenshot 2022-08-08 at 18 38 32" src="https://user-images.githubusercontent.com/93924525/183479689-d81cc33d-28bd-49de-8586-1b605f358c7f.png">

**Comment by kdembler** [comment]
Let's tackle 1️⃣ in https://github.com/Joystream/marketing/issues/278, added there

**Comment by bedeho** [comment]
> Do we need to specify the podcast Episode number here?

I guess not ;)

**Comment by dmtrjsg** [comment]
Let's remove the Episode Number :)

**Comment by kdembler** [comment]
@dmtrjsg It's done here https://github.com/Joystream/joystream-org/pull/532
