### ISSUE TITLE
Update CTA for Joystream.org CRT user testers recruitment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#285]
## Context

We've had an issue reported by community, which indicated that the current CTA is misleading. 

[Here's the link>](https://github.com/Joystream/joystream/issues/4226#issue-1353444225)

## Scope

- [ ] Update "Sign up for Beta Test" to "Sign up to Usability Testing"

![Screenshot 2022-08-29 at 09.52.44.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/e131f6fd-89fb-49c4-b0b5-2c276177b27a)

**Comment by MindsGaming** [comment]
Awesome 😎

**Comment by dmtrjsg** [comment]
We have 30+ participants
