### ISSUE TITLE
Multiple Gateways for project homepage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#289]
## Context

Multi-gateway set up for the OB journey, covered here:
- https://github.com/Joystream/atlas/issues/3273

Implications on website covered in this issue

Website: Right now, the website has a few key CTAs saying Claim your channel, talking directly to creators, primarily because the whole site speaks very directly to creators, not because we were expecting that creators were going to land on the main project website as part of the natural signup flow, they were not. 

It may however be more prudent now to clarify things by either replacing this CTA, or having it send you to a section or new page which shows an overview of apps/gateways which you can get onto. This should also explain how these are different apps built on one platform. The Jsgenesis app would merely be one of these.

## Scope
- [ ] Update the project homepage copy wrt to multiple Gateways / Apps supported by joystream blockchain and dao.
- [ ] Update CTAs from "Claim channel" to smth like "View Apps"
- [ ] Create intermediate page which would feature all Apps connected to joystream blockchain. 

Suggestions for the latter: Apps are most likely to occupy a certain content vertical. Two first apps to be featured on the page will be supported by JSG. Gleev (Web3 focus, run by JSgenesis) and ~Vinteo (Broad category span, to accommodate all video content that falls outside of Gleev)~. The page must be designed in a way where 1 Apps looks, but can be extended up to 10+ without having to redesign the page. Add a CTA to invite users to set up their own gateway via Link to GH page dedicated to it.

NB: After design work is done, this issue will be transferred to monorepo for implementation.

**Comment by toiletgranny** [comment]
Note to self: start with low-if sketches

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/atlas #3321](https://github.com/Joystream/atlas/issues/3321) via [**Zenhub**](https://www.zenhub.com/)
