### ISSUE TITLE
A list of creators for Gleev

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#295]
# Background

Jsgenesis will be launchin Gleev, which will be a version of Atlas focused on the Web3 space. Its not clear exactly when it will become publicly accessible and marketed, but onboarding initial creators will only start once YPP works technically and operationally, which will be some time after mainnet launch at current pace. It would be a good idea to launch to the public with some initial set of creators, so the product is not empty, and there is some initial awareness, and this is a process I will be involved in through the form of creator outreach. There may also be a place for volunteers to help, but Gleev is strictly not operated or funded by the DAO, only Jsgenesis, but it would be in the interest of the DAO to contribute to it's success and growth as a first app.

# Proposal

It would be great if the Marketing working group could contribuet to compiling a database, e.g. on Notion, which contains a list of Web3 focused content creators that are active on YouTube. This is a list we can use to generate leads to approach people for early access to  Gleev.

Here is an example schema
- Channel name
- Email (if visibl on the info page)
- Personal website
- Channel URL
- Twitter handle
- Date added to database
- Number of videos
- Number of followers
- Number of videos published the last month
- Days since last video
- Language spoken in videos
- Description on YouTube
- Topic: tags can work for this, like `trading`, `interviews`, `polkadot`, etc.

**Comment by Songoku1691** [comment]
Wow! This is great and exciting Sir!
Aside from web-3 focused youtube channels, I think we must also invite some non-crypto related channels just to have some substance in our contents.

**Comment by bedeho** [comment]
> Aside from web-3 focused youtube channels, I think we must also invite some non-crypto related channels just to have some substance in our contents.

No, that is not what `Gleev` is about, its very narrowly focused, its not trying to be a general content platform, its focused on only web3, at least for now. Others can build more general gateways if they want.

**Comment by Songoku1691** [comment]
Understood Sir.

**Comment by mariofandom** [comment]
ПриветЮ я могу помочь составить список русскоязычных криптоканало в телеграм и ютуб

**Comment by ismail34603** [comment]
Here we can track performance of [Maria](https://dao.joystream.org/#/members/3082) for 30th term: https://www.notion.so/joystream/30th-Term-2d33b9b7fe904e039987704fcd5a8f5d 

Here we can track performance of [Jpaul](https://dao.joystream.org/#/members/4354) for 30th term: https://www.notion.so/joystream/30th-Term-df87b153b6674171bee23ffcbf233828 

Here we can track performance of [swargo](https://dao.joystream.org/#/members/2532) for 30th term: https://www.notion.so/joystream/30th-Term-77e13384f2fb49b49602cd9ae6a2f73f 

Here we can track performance of [riezza](https://dao.joystream.org/#/members/3594) for 30th term: https://www.notion.so/joystream/30th-Term-03dee5027f734e479cce91fee8196c78

**Comment by ismail34603** [comment]
Here we can track performance of [Maria](https://dao.joystream.org/#/members/3082) for 30th term: https://www.notion.so/joystream/31th-Term-b6c76c180a96463785f6f0b59efc4ae5

Here we can track performance of [Jpaul](https://dao.joystream.org/#/members/4354) for 30th term: https://www.notion.so/joystream/31st-Term-4fd637ed527d44f6bb52ef04e98cccf1

Here we can track performance of [swargo](https://dao.joystream.org/#/members/2532) for 30th term: https://www.notion.so/joystream/31th-Term-a3807f80b7484ba6a35cb504a8ddebea 

Here we can track performance of [riezza](https://dao.joystream.org/#/members/3594) for 30th term: https://www.notion.so/joystream/31th-Term-87777ce5ed19423ea8e9cd864ff8a70e 

Here we combine all listings each term: https://www.notion.so/joystream/Master-sheet-ffe981fa016f442c9833928636222f2d

**Comment by ismail34603** [comment]
Here we can track performance of [Jpaul](https://dao.joystream.org/#/members/4354) for carthage early days (unpaid and volunteer work): https://joystream.notion.site/Carthage-early-days-f8e3617055a64bd89353bbd0dedc6c9d 

Here we can track performance of [swargo](https://dao.joystream.org/#/members/2532) for carthage early days (unpaid and volunteer work): https://joystream.notion.site/Carthage-early-days-e4fddf5e8d7044eeb824ce6d30373b02

Here we can track performance of [riezza](https://dao.joystream.org/#/members/3594) for carthage early days (unpaid and volunteer work): https://joystream.notion.site/Carthage-early-days-c4f733dd7eee4b73ba587446facac48c
