### ISSUE TITLE
Smörgåsbord Design Brief

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#297]
# Disclaimer

This whole thing was rushed, and is probably underspecified, a meeting is probably in order 😓 .

### Tracking

Pre-launch scope
- #298
- #312 
- #301 
- #303 
- #305 
- #306 
- #307 

Post-launch scope
- #304 
- #308  
- #316

# Mainnet Launch

- **Mainnet Illustration:** The centrepiece of the branding for all network launches has been some motif that corresponds to the location name of the network. We have nothing like this for the mainnet. Mainnet really is just called "mainnet", but the pattern of using location names is something that works pretty well, so we may end up using it post-mainnet also. If complex illustrations are needed, then I can ask a skilled illustrator in our community to do the work, but I will leave it to you to decide what the motif should actually be. We have standard covers that are derivatives of the main illustration, that we use for twitter and the blog, but if the new illustration is very different, then new derivative covers would be needed. _I would prefer if we can try to have some illustration that works well with the old style, just to minimize complexity._
- **Launch:** The launch itself occurs in stages. You can read about the purpose and substance of each stage here https://github.com/Joystream/joystream/issues/3792, but no need to get into the nitty gritty details. If you feel you need deeper information than you can glean in a reasonable amount of time from this to do a proper good job, then just ping me. There are a number of milestons for which we will need some communication materials
  - **Announcement:** As per normal, we need to actually announce the mainnet, which is in the form of a Twitter & blog post. You can find many examples of these online.
  - **Mainnet in X day(s)**: A countdown post we can use to post regularly as we count down to last day before launch. Great if we could have distinct versions for double and single digit days, at least if design does not work out of the box for both.
  - **Mainnet is Live:** We also need a separate set of assets for launch. We launch in the **Frozen** stage, but this is not something we need to detail in the imagery, it can be explained in the blog post.
  - **Thawn, Supervised, Liberated**: Each one of these are milestones on the path to being a full autonomous and operational network, and each deserves an announcement post, possibly also including a blog post.
  - **Validator Limit Updated:** At various points in time, the number of validators allowed in the system will be changed, and this is an important signal both to validators and to the community. We start at 9, but then we will increase in 5-10 size increments, probably up to high double digit count, or 100. This just requires a twitter image, no blog post image.

# Gleev

My assumption is that, when we announce Gleev in way that is public, YPP will be available. It may be the that Gleev is up and running before we make the announcement, e.g. in some grace period, but we would not be doing any announcement or outbound marketing to get third parties to join or refer their peers.

Twitter will be the primary social media home for Gleev, but there will also be a blog "blog.gleev.xyz", so we need

1. A cover image for Twitter page.
2. A cover image for Twitter post and blog post for launch announcement: I may ask for help with visuals inside the post itself, but that would be later.
4. A cover image for Twitter post for announcement message when a creator signs up, sort of like this: https://twitter.com/XcademyOfficial/status/1593586922991091713.
5. A cover image for Twitter post for announcement message for when payout occurs: Could be useful to include some simple highlight, like total payout, max earner, whatever you think makes it interesting.
6. A cover image for Twitter post and blog post for for announcement that the YPP program is live, which will link to blog.

# Joystream.org Enhancements

## Landing Page

- Drop section: "We’re building Joystream to set it free"
- Drop section: "Investors"
- Typo: "... with _a_ handful ..."

and in footer

- Drop "Github" footer column, has just one link which is already coveredunder "follow us".
- Add "Security" in one of the columns, and it should be a mail-to link to "security@joystream.org"
- Add "Block Explorer" in one of the columns, and it should link to "https://polkadot.subscan.io/"
- Drop "Useful links": tokenomics should not be a dedicated link, and that just leaves "brand guideance"-

Feel free to propose alternative content which works better in footer, because after these changes there will only be two columns left, if you think that is a problem.

## NEW: Token Page

The current token page if focused on [$tJOY](https://www.joystream.org/token/), which is no longer relevant. We need a new token page focused on explaining $JOY a bit better, and here are some reference examples of other project pages for this
- https://subsocial.network/token
- https://polkadot.network/dot-token/
- https://polygon.technology/matic-token

Here is one possible structure:

- "Token in numbers": I suggest we keep this section, and just drop the headline, and have fields
   - Symbol: $JOY
   - Supply: the number of $JOY, starts at
   - Price: price of $JOY in $USD, needs not available variation
   - FDV: $USD value of fully diluted market cap, needs not available variation
- FAQs: like now basically, just with a few questions in there, we can specify them later.
- "Wallets": a section showing different wallets that are supported.
- "Faucets": Here we want a section which basically reminds people that you can try at least two known apps, Gleev and Pioneer, where they can get some small initial quantity to create their own profile.
- "Exchanges": Here we would show list of exchange venues for obtaining the token. Here we need a variation which says something like, "the token is not known to be traded on any exchange at this time."
- "Earn": Here we basically want to point out that there are a range of activities which allow you to earn the token.
- "Utility": A section about what the token allows you to do
   - Elections: Both stand for and vote in council elections
   - Nominate Validators:
   - Proposals: Create and discuss proposals to change the the operation or rules of the system, or allocate resources.
   - Work: in working group
   - Publish: make your profile, publish content.
   - Interact: make comments, react to content and join the forum.
   - Invest and support: Buy and trade NFTs and Creator Tokens.
- "Supply Dynamics": A section where we explain that the supply is not fixed, but is subject to perpetual minting and burning events.
   - Mint: The following events cause minting new $JOY
      - Rewards for validators
      - Rewards councilors, workers and leads
      - Rewards for creators
      - Rewards for applications
      - Financing spending proposals and bounties
   - Burn: The following events cause burning of $JOY
      - Creator token sale
      - NFT Sale
      - Application fee
      - Publishing content

## UPDATE: About page

- We should go to a model of not elevating or otherwise distinguishing the Jsgensis vs community affiliated members that are responsible for the project, and we also want to make it clear that this page is a story about who was part of _launching_ the system, and that now. I suggest we display all foudning members, sort of in a style like this https://chain.link/team, where we show avatar, handle and memberid, in a sort of more uniform neutral grid. I believe we already have more than 100 founding members, certainly when you include Jsgenesis affiliated folks, probably closer to 150.
- We can have all investors in a distinct section under the founding member section.

## NEW: Community page

We should have a dedicated page to aggregate all links to any off-site resource that is helpful both for the community and for newcomers, sort of like this: https://polkadot.network/community/

Form what I can think of, we need
- Twitter
- Reddit
- Github
- Handbook link
- Element chat
- Mailinglist
- Discord
- Gleev channel
- Youtube channel.

## UPDATE: Mainfesto page

Update https://www.joystream.org/manifesto/.

In general looks "bad", low quality. Text is distorted in unsystematic and bad ways, even leaving important parts smaller, as if designer did not actually read content. Having less and less prominent imagery, and more focus on beautiful typography and proper use of space, which supports the content, would be great.

## UPDATE: Primer page

**TBD.**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203434159261233) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Thanks so much for putting it all together! Rushed or not rushed, most of what you wrote is clear to me. 😇 I would, however, appreciate clarifying a few things I listed below in the "Questions" section.

Once I have the full picture, I'd be happy to share my rough time estimations with you guys so that @dmtrjsg can join and do his magic with all the planning, prioritizing, and logistics. If I may, Dima, I believe it would be helpful to break each chunk of work that @bedeho has mentioned into separate GH issues to keep the further discussion more focused.

### Questions:
1. What does _Smörgåsbord_ stand for? I know what it means in Swedish, but I just wonder whether it acts as a name for something else.
2. Does the order in which you mention these chunks of work reflect the ideal order in which you want to have it delivered?
3. **Mainnet Launch:**
   1. **Mainnet Illustration:** Just to make sure I understand what you mean by the "main illustration" and a "cover" that's a derivative of that main illustration, can you confirm that [this](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=225%3A770&t=Gos3osuBPNMC8Oct-4) is what you refer to as a "main illustration" for the Giza release, while [this](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=228%3A3156&t=Gos3osuBPNMC8Oct-4) and [this](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=230%3A68451&t=Gos3osuBPNMC8Oct-4) are the covers in this case?
   2. **Mainnet in X day(s):** Has anything like that been created before for Joystream? If not, do you have anything specific in mind? Like, for example, a series of cover images for Twitter posts with a prominent "5 days left until mainnet launch"?
   4. **Mainnet is Live:** By the "set of assets", did you mean a cover image for a Twitter post and an image for a blog post?
   5. **Thawn, Supervised, Liberated:** Do you recon that a variation of the main "Mainnet Illustration" would work to illustrate these? Or does each milestone deserve its own custom illustration, just like each release?
   6. **Validator Limit Updated:** Similarly to the "Mainnet in X day(s)", has anything like this been created before? Would a simple image with a prominent number, a smaller caption underneath, and perhaps some brand patterns in the background work? Or do you have something specific in mind?
3. **NEW: Token Page**
   1. **"Earn":** How many activities are there? Is it possible for you to list them here, to help understand scale and complexity of this section?
4. **UPDATE: About page**
   1. So, just the grid of founding members, and that's it for the About page? Are we dropping the "Open positions" section?
5. **UPDATE: Mainfesto page**
   1. Is it just a visual overhaul, or is there anything else we would be changing about this page? Does the content stay the same?

**Comment by toiletgranny** [comment]
@bedeho @dmtrjsg Below are my first rough estimations based on the _assumptions_ I'm making in my questions above.

### Estimations (total: ~14-22 days)

1. **Mainnet Launch:** (total: 15-21 hrs / 2.5-3.5 days)
   - **Mainnet Illustration:** 6-12 hrs (including technical prep time, research on the subject of illustration, consulting and exchanging feedback on ideas, doing the final illustration, and iterating on it)
   - **Launch:**
        - **Announcement:** 1 hr,
        - **Mainnet in X day(s):** 2 hrs,
        - **Thawn, Supervised, Liberated:** 4 hrs,
        - **Validator Limit Updated:** 2 hrs,
2. **Gleev:** (total: 6.5 hrs / 1 day)
   - **A cover image for Twitter page:** 0.5 hrs,
   - **A cover image for Twitter post and blog post for launch announcement:** 1 hrs,
   - **A cover image for Twitter post for announcement message when a creator signs up:** 2 hrs,
   - **A cover image for Twitter post for announcement message for when payout occurs:** 2 hrs,
    - **A cover image for Twitter post and blog post for announcement that the YPP program is live:** 1 hrs,
3. **Joystream.org Enhancements** (total: 60-104 hrs / 10-17 days)
   - **Landing Page**: 2-4 hrs,
   - **NEW: Token Page:**
       - about 1.5-2 weeks with both low-fidelity (just like the last time) and high-fidelity and handover,
       - about a week with just the high-fidelity mockups and handover,
   - **UPDATE: About page:** 8-12 hrs,
   - **NEW: Community page:** 12-16 hrs,
   - **UPDATE: Mainfesto page**: 8-12 hrs.

**Comment by dmtrjsg** [comment]
Will break it down to issues for easier workflows. 

Re order we first need to start with the marketing collaterals and landing page and banners so we have the necessary parts done 100% for the launch. 

Joystream.org enhancements would go as second wave, starting with the Landing page and banners. 

👍

**Comment by bedeho** [comment]
> What does Smörgåsbord stand for? I know what it means in Swedish, but I just wonder whether it acts as a name for something else.

Well, I just used it to reflect the rather chaotic and mixed nature of the tasks in this brief, as if they were bunch of different sandwiches and treats, like this

![swedish-midsummer-smorgasbord-2848988303](https://user-images.githubusercontent.com/437292/203353070-34d7f76c-efdc-4ee5-9cd0-7d27ba5a8e8f.jpg)

> Does the order in which you mention these chunks of work reflect the ideal order in which you want to have it delivered?

Yeah I think just doing it all in order of listing is perfectly fine.

> Mainnet Illustration: Just to make sure I understand 

Correct.

> Mainnet in X day(s): 

I can't think of any actually, you would advise against it?

> Mainnet is Live:

Correct.

> Do you recon that a variation of the main "Mainnet Illustration" would work 

They probably _should_, not only can, be derivative or variations.

> Validator Limit Updated: 

Not that I know of, just share the simplest thing you can think of.

> How many activities are there? Is it possible for you to list them here, to help understand scale and complexity of this section?

Probably this list https://joystream.gitbook.io/testnet-workspace/#opportunities  as base, but drop "refer-a-friend", all the "lead"  variations,  and then add content creator.

> So, just the grid of founding members, and that's it for the About page? Are we dropping the "Open positions" section?

Yeah just drop that, not sure it was ever much used.

> Is it just a visual overhaul, or is there anything else we would be changing about this page? Does the content stay the same?

Just visual, content could probably be changed also, refined. Not sure if it's ok to change now, but I think the design should not be so sensitive to the presence or removal of a paragraph.

**Comment by bedeho** [comment]
I also just realised I  missed on  thing: we need a new twitter cover for our main Joystream twitter page also, something not-horrible (like  we have now), and something that perhaps signals that we are on mainnet, as many people will have followed us for a long time on testnet.

**Comment by toiletgranny** [comment]
@bedeho Thanks for the replies.

> Well, I just used it to reflect the rather chaotic and mixed nature of the tasks in this brief, as if they were bunch of different sandwiches and treats, like this

Of course, I see. For a second I thought it's an IKEA-inspired name for some post-mainnet launch release. But now I see how it all connects. 

:D

> Just visual, content could probably be changed also, refined. Not sure if it's ok to change now, but I think the design should not be so sensitive to the presence or removal of a paragraph.

Of course not.

> I also just realised I missed on thing: we need a new twitter cover for our main Joystream twitter page also, something not-horrible (like we have now), and something that perhaps signals that we are on mainnet, as many people will have followed us for a long time on testnet. Perhaps also more aligned with new landing page.

Of course, adding to the scope of https://github.com/Joystream/marketing/issues/298.
