### ISSUE TITLE
Mainnet launch illustrations

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/marketing#298]
This ticket tries to part of the scope mentioned in the https://github.com/Joystream/marketing/issues/297

> # Mainnet Launch
> * **Mainnet Illustration:** The centrepiece of the branding for all network launches has been some motif that corresponds to the location name of the network. We have nothing like this for the mainnet. Mainnet really is just called "mainnet", but the pattern of using location names is something that works pretty well, so we may end up using it post-mainnet also. If complex illustrations are needed, then I can ask a skilled illustrator in our community to do the work, but I will leave it to you to decide what the motif should actually be. We have standard covers that are derivatives of the main illustration, that we use for twitter and the blog, but if the new illustration is very different, then new derivative covers would be needed. _I would prefer if we can try to have some illustration that works well with the old style, just to minimize complexity._
> * **Launch:** The launch itself occurs in stages. You can read about the purpose and substance of each stage here [Carthage rollout plan joystream#3792](https://github.com/Joystream/joystream/issues/3792), but no need to get into the nitty gritty details. If you feel you need deeper information than you can glean in a reasonable amount of time from this to do a proper good job, then just ping me. There are a number of milestons for which we will need some communication materials
>   
>   * **Announcement:** As per normal, we need to actually announce the mainnet, which is in the form of a Twitter & blog post. You can find many examples of these online.
>   * **Mainnet in X day(s)**: A countdown post we can use to post regularly as we count down to last day before launch. Great if we could have distinct versions for double and single digit days, at least if design does not work out of the box for both.
>   * **Mainnet is Live:** We also need a separate set of assets for launch. We launch in the **Frozen** stage, but this is not something we need to detail in the imagery, it can be explained in the blog post.
>   * **Thawn, Supervised, Liberated**: Each one of these are milestones on the path to being a full autonomous and operational network, and each deserves an announcement post, possibly also including a blog post.
>   * **Validator Limit Updated:** At various points in time, the number of validators allowed in the system will be changed, and this is an important signal both to validators and to the community. We start at 9, but then we will increase in 5-10 size increments, probably up to high double digit count, or 100. This just requires a twitter image, no blog post image.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203434159584935) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@bedeho Below is a list of 10 possible motifs for the mainnet launch illustration, varying from historically significant locations to symbols and creatures from Greek mythology. I marked my recommendations with a ⭐ icon.

1. [Locations, architecture] **Temple of Artemis, Ephesus**
    
    > The Temple of Artemis or Artemision, also known as the Temple of Diana, was a Greek temple dedicated to an ancient, local form of the goddess Artemis (identified with Diana, a Roman goddess). It was located in Ephesus (near the modern town of Selçuk in present-day Turkey).
    
    ![image](https://user-images.githubusercontent.com/35307309/203363480-e8dabb49-fae5-4e4c-a155-4471086557a9.png)
    
2. [Locations, architecture] **Temple of the Sun, Machu Picchu**
    
    > The Temple of the Sun was a sacred precinct built by the Incas to pay tribute and give offerings to the sun inside Machupicchu. This star was one of the most important deities of the Inca civilization. Thus, only the priests and the elite of the empire could enter this temple.
    
    ![image](https://user-images.githubusercontent.com/35307309/203363646-55312a7e-4775-42c4-84f6-aec4f37f542d.png)

    
3. [Locations, architecture] **Lion Gate, Mycenae**
    
    > Lion Gate is the popular modern name for the main entrance of the Bronze Age citadel of Mycenae in southern Greece. The gate is the sole surviving monumental piece of Mycenaean sculpture. as well as the largest surviving sculpture in the prehistoric Aegean. It is the only monument of Bronze Age Greece to bear an iconographic motif that survived without being buried underground.
    
    ![image](https://user-images.githubusercontent.com/35307309/203363856-80c10199-aea4-4e5e-9554-34ff83072f95.png)

4. [Architecture] **Temple of the Great Jaguar, Tikal**
    
    > Tikal Temple I is the designation given to one of the major structures at Tikal, one of the largest cities and archaeological sites of the pre-Columbian Maya civilization in Mesoamerica. It is located in the Petén Basin region of northern Guatemala. It also is known as the Temple of the Great Jaguar because of a lintel that represents a king sitting upon a jaguar throne.
    
    ![image](https://user-images.githubusercontent.com/35307309/203363988-cb235045-6715-4c37-808b-d99e31b6e78d.png)
    
5. [Architecture] **El Castillo, Chichen Itza**
    
    > El templo, known as the Temple of Kukulcán (or also just as Kukulcán), is a Mesoamerican step-pyramid that dominates the center of the Chichen Itza archaeological site in the Mexican state of Yucatán. Built by the pre-Columbian Maya civilization sometime between the 8th and 12th centuries AD, the building served as a temple to the deity Kukulcán, the Yucatec Maya Feathered Serpent deity closely related to Quetzalcoatl, a deity known to the Aztecs and other central Mexican cultures of the Postclassic period. It has a substructure that likely was constructed several centuries earlier for the same purpose.
    
    ![image](https://user-images.githubusercontent.com/35307309/203364087-b7813628-0362-44fe-b7dd-183a5341e3d3.png)
    
6. [Mythology, creatures] **Pegasus**
    
    > Pegasus is one of the best known creatures in Greek mythology. He is a winged divine stallion usually depicted as pure white in color. He was sired by Poseidon, in his role as horse-god, and foaled by the Gorgon Medusa. He was the brother of Chrysaor, born at a single birthing when his mother was decapitated by Perseus. Greco-Roman poets wrote about his ascent to heaven after his birth and his obeisance to Zeus, king of the gods, who instructed him to bring lightning and thunder from Olympus.
    
    ![image](https://user-images.githubusercontent.com/35307309/203364189-bcc9f787-640a-4502-8314-c8043094513b.png)

   💡 By the way, the horse in the above photograph is on the roof of Opera House in Poznań, my hometown. 
    
7. ⭐ [Mythology, creatures] **Griffin**
    
    > The griffin, griffon, or gryphon is a legendary creature with the body, tail, and back legs of a lion; the head and wings of an eagle; and sometimes an eagle's talons as its front feet. Because the lion was traditionally considered the king of the beasts, and the eagle the king of the birds, by the Middle Ages, the griffin was thought to be an especially powerful and majestic creature. Since classical antiquity, griffins were known for guarding treasures and priceless possessions.
    
    ![image](https://user-images.githubusercontent.com/35307309/203365032-21653f71-8efc-4e7f-a36a-c00e0461522e.png)
    
8. [Mythology, creatures] **Phoenix**
    
    The phoenix is an immortal bird associated with Greek mythology (with analogs in many cultures) that cyclically regenerates or is otherwise born again. Associated with the sun, a phoenix obtains new life by rising from the ashes of its predecessor. Some legends say it dies in a show of flames and combustion, others that it simply dies and decomposes before being born again.
    
    ![image](https://user-images.githubusercontent.com/35307309/203365496-ce67d69c-054b-462b-8522-40dedc442a0b.png)
    
9. [Mythology, symbols] **Cornucopia**
    
    > In classical antiquity, the cornucopia, also called the horn of plenty, was a symbol of abundance and nourishment, commonly a large horn-shaped container overflowing with produce, flowers, or nuts. Mythology offers multiple explanations of the origin of the cornucopia. One of the best-known involves the birth and nurturance of the infant Zeus, who had to be hidden from his devouring father Cronus. In a cave on Mount Ida on the island of Crete, baby Zeus was cared for and protected by a number of divine attendants, including the goat Amaltheia ("Nourishing Goddess"), who fed him with her milk. The suckling future king of the gods had unusual abilities and strength, and in playing with his nursemaid accidentally broke off one of her horns, which then had the divine power to provide unending nourishment, as the foster mother had to the god.
    
    ![image](https://user-images.githubusercontent.com/35307309/203365279-a9677418-b9e1-4b67-ac1f-8586ec1f50db.png)
    
10. ⭐ [Mythology, symbols] Atlas
    
    > In Greek mythology, Atlas is a Titan condemned to hold up the heavens or sky for eternity after the Titanomachy. Atlas also plays a role in the myths of two of the greatest Greek heroes: Heracles (Hercules in Roman mythology) and Perseus. According to the ancient Greek poet Hesiod, Atlas stood at the ends of the earth in extreme west. 
    
    ![image](https://user-images.githubusercontent.com/35307309/203365325-81cbe9b9-e546-4112-98e6-730be52ed69a.png)

**Comment by toiletgranny** [comment]
Excellent, let's go with Pegasus, then. 

> I will get someone to start on this asap.

Do you mean finding someone to create an actual illustration? If so, then great! But, just so you know, if you have difficulties finding someone who's available right now, I could certainly give this a shot myself. In fact, the estimations I provided [in this comment](https://github.com/Joystream/marketing/issues/297#issuecomment-1323639074) were based on the assumption that I'd be creating the illustration myself. So the option is there if you want it.

**Comment by bedeho** [comment]
Oh, I did not know that, I did not know you did illustrations, sorry :(. This person has already started, promised something by noon today, so sorry :(

**Comment by toiletgranny** [comment]
@bedeho As per our conversation on Discord yesterday evening, I did the horse. Three, in fact, so that you guys can pick your favorite. cc @dmtrjsg 

### Option A
The first option started out being quite ambitious in terms of the technical quality but ended up being a bit rushed toward the end once I realized I'd already spent 8 out of the 12 hours I estimated initially for the entire thing. Hopefully, you can't tell this was the case just by looking at the end result.

![image](https://user-images.githubusercontent.com/35307309/203820061-1281aeb5-befd-423b-92dd-f10f91c88b90.png)

### Option B

With the second option, I went for perhaps a bit unconventional portrayal of Pegasus, but it's because I really wanted for this option to reflect the cutting-edge nature of what we're all doing here. I'd understand if that's not your favorite, though. Just be honest.

![image](https://user-images.githubusercontent.com/35307309/203825679-7aa698cd-e051-4d55-9fde-64fe5f55da9b.png)

### Option C

This is what I call a "backup plan". If none of the above satisfies your preferences, I put together this third option to follow the already established visual style for Joystream illustrations used for testnet releases. [You can open up this Figma file to see how the illustration compares looks like against previously created ones. ](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=229%3A35048&t=4LUBu8BqOm6pNcul-1)

In all seriousness now, please don't hesitate to leave your honest feedback on this. I think I already got the hang of the process of creating this, so introducing adjustments or experimenting with things like wings or a different perspective of the horse should not be a big deal at this stage. 

![image](https://user-images.githubusercontent.com/35307309/203826160-afebf6a3-a526-4dcf-a18f-a8e1faff93d6.png)
![image](https://user-images.githubusercontent.com/35307309/203827039-26c1f3c0-ecea-4f21-ba77-a02230b5ae53.png)

**Comment by dmtrjsg** [comment]
Its a tough choice here 🤣 I'm on the fence need to sleep over it and will let you know tomorrow on a fresh look.

**Comment by bedeho** [comment]
1. I'm a sucker for A here, but feels a bit off brand 🤣 
2. I think you've done realyl well on the horse, and I have to say quite quickly. I think it would be easier to feel how well it works, even without any improvement, by showing how it will look on the different cards.
3. When I looked at this, it actually did make me reconsider: is using a pegasus the right approach? I wonder, as the network will just be called "mainnet", it won't literally be called _Pegasus_ as that would just be confusing. So then its called mainnet, and there is this random horse there. Will that also just be confusing? How do you think it could work ot just do something much more mundane, like this
  - https://twitter.com/graphprotocol/status/1339642891728166912
  - https://medium.com/avalancheavax/avalanche-mainnet-is-live-c2101c82ce10
So we basically move away from having like a dedicated animal or city, and more just embrace the literal message, and use text as primary motif. Hate to come and suggest this now, but I just wonder how well the Pegasus will work in the end, regardless of how well you do it.

**Comment by toiletgranny** [comment]
@bedeho Due to my somewhat emotional attachment to the horse, I hate to admit that you make very compelling arguments. 

Regarding this more mundane approach, we need to keep in mind that with Joystream's branding, things like typography and other brand elements are toned down compared with the examples you brought up. As I can imagine, the reason behind this is to make visual space for these distinctive and expressive Joystream illustrations. Therefore, if we want to rely on typography alone, the end result might end up feeling a bit empty as long as we want it to still feel like Joystream.

Having said that, I'm happy to explore this direction from multiple angles. I'll prepare a few options for the Announcement Twitter post cover so that we can see it in context.

And while I'm at it, I would also love to give the horse a shot anyway. Perhaps it's not a lost cause yet, and there's still a way to have it being key visual of the mainnet launch without feeling like it's just another testnet network. 

cc @dmtrjsg

**Comment by toiletgranny** [comment]
@bedeho Twitter cover images are ready to be reviewed [in this Figma file](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=2315%3A83036&t=Bt9duekoP30MQuab-1). For each cover image, I put together a set of alternative options for you to choose from.

Please, let me know which cover image you like the most for each cover image so that I can create a blog image for that. 

Optionally, as I realize how important of an announcement the `Mainnet is Live` is, I can try to put together an animated version of this post using the [animation templates we created in the past](https://github.com/Joystream/atlas/issues/1844#issuecomment-1026853545). You know, flashing background, blinking text, whatever it takes to help it really stand out. Of course, all within the boundaries of good taste. Let me know if you'd like that — shouldn't take more than 1-2 hours.

**Comment by bedeho** [comment]
> For each cover image, I put together a set of alternative options for you to choose from.

They all look fantastic, left feedback, I expect we can just mix and match the different variations as we find practical, great to have some variety. For the blogs I have indicated a favorite.

> I can try to put together an animated version of this post using the https://github.com/Joystream/atlas/issues/1844#issuecomment-1026853545

No that is fine.

**Comment by toiletgranny** [comment]
Thanks, @bedeho! I reviewed and addressed all your comments in Figma. Since you asked me to keep the alternative versions, I just changed the copy as per your request, cleaned up the files, set the export presets in Figma, and created blog covers for the versions you pointed out. 

Once again:
1. [Here you can find all Twitter cover images in Figma](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=2315%3A83036&t=8yD9h9Plzl6XqokX-1),
2. And [here you can find all blog post cover images in Figma](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=2331%3A82211&t=8yD9h9Plzl6XqokX-1). 
   - I noticed that you guys have been using images of different dimensions as blog post covers in the past — `1300 x 800` and `1200 x 675`. Not knowing which dimensions are used now, I just created 2 versions of each blog post cover hoping you'll know which one to use.

Since I remember you know how to use Figma at a basic level, let me know if you'd want my help in exporting the images to any specific location (a GitHub repo or something).

**Comment by traumschule** [comment]
Was going to ask: Is it to be a unicorn in the clouds? And there is option B! (preferable without the plane wings though)

Of course it's "just" mainnet with Ephesus another location in sight, so it won't stick for long and also good to have space for upwards expansion later on. Compared to other projects that launch with one mascot Joystream has periodic transformations built-in (which eradicates Phoenix for any release imo).
With the horse we hold on to antique transportation with plenty of options to "modernize" and "lift off" in years to come.

(again just rambling since you'r in the final lap already)

**Comment by toiletgranny** [comment]
@traumschule Thanks for chiming in! While I do agree with your observations, we already launched the mainnet communication on JS social media channels and we decided not to use any custom illustration whatsoever for communicating mainnet, not to overshadow the core message.

**Comment by toiletgranny** [comment]
@bedeho [Under this Figma link](https://www.figma.com/file/8Lxg4hkrsJ1q3kjAHPE9ha/Joystream-%7C-Network-Logos%26Assets?node-id=2368%3A82211&t=yLIs8pdRWl2NA9H1-1) you'll find the one last missing piece, Twitters's background cover image for the JS profile. 

Just like the last time, I cooked up with a few options for you to pick from and I put my recommendation at the top. It might come across as a bit too playful for the Joystream previous visual language, but I thought — what the heck — you only announce the Mainnet launch once (hope i'm not mistaken).

**Comment by toiletgranny** [comment]
@dmtrjsg I believe this issue can now be closed.
