### ISSUE TITLE
Mainnet Joystream.org: Landing Page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#303]
## Context
- https://github.com/Joystream/marketing/issues/297

### Landing Page

- Drop section: "We’re building Joystream to set it free"
- Drop section: "Investors"
- Typo: "... with _a_ handful ..."

and in footer

- Drop "Github" footer column, has just one link which is already coveredunder "follow us".
- Add "Security" in one of the columns, and it should be a mail-to link to "security@joystream.org"
- Add "Block Explorer" in one of the columns, and it should link to "https://polkadot.subscan.io/"
- Drop "Useful links": tokenomics should not be a dedicated link, and that just leaves "brand guideance"-

Feel free to propose alternative content which works better in footer, because after these changes there will only be two columns left, if you think that is a problem.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203434106470729) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
I updated the designs exactly as specified in the above scope. This issue is ready for implementation.

**Comment by dmtrjsg** [comment]
Pointers for easier navigation:

1. Typo to be fixed here: 
<img width="751" alt="Screenshot 2022-11-29 at 20 46 05" src="https://user-images.githubusercontent.com/93924525/204590685-faf92961-c37d-4882-bad6-b4f6b65ef987.png">

2. Dropped sections are implemented in Adam's updated figma link: 

<img width="599" alt="Screenshot 2022-11-29 at 20 45 51" src="https://user-images.githubusercontent.com/93924525/204590818-9f4c422b-ac0f-454b-9ed2-52f215856ccf.png">

3. Footer updated:
<img width="705" alt="Screenshot 2022-11-29 at 20 47 34" src="https://user-images.githubusercontent.com/93924525/204591049-ccac3519-d2e9-4a74-bbeb-8f7a9f199cf2.png">

**Comment by dmtrjsg** [comment]
Implemented here: https://github.com/Joystream/joystream-org/pull/560
