### ISSUE TITLE
Mainnet Joystream.org:  Manifesto Page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#307]
## Context
- https://github.com/Joystream/marketing/issues/297

## UPDATE: Mainfesto page

Update https://www.joystream.org/manifesto/.

In general looks "bad", low quality. Text is distorted in unsystematic and bad ways, even leaving important parts smaller, as if designer did not actually read content. Having less and less prominent imagery, and more focus on beautiful typography and proper use of space, which supports the content, would be great.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203434118858816) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@bedeho @dmtrjsg Ready to be reviewed. I put together five options, so be sure to enable comments in Figma (`Shift + C`), as I left a couple of notes here and there to help you find all the differences between them. We can also mix and match if you want, e.g. if you prefer the style of highlights from the version D, but like the pattern section dividers from the version A, that's totally cool.

> **Warning**
>  @bedeho, since you mentioned typography and using white space, a reminder that pressing `Shift + 0` in Figma will set the zoom level to 100%, giving you the most accurate representation of the scale in which the website will be rendered in the browser, once implemented. 
>> **Note**
>>  Pressing `Shift + 1` will set your Figma viewport to fit everything in view.

**Figma links:**
- Inspect mode: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=7304%3A401368&t=HTFUe4NBNpdzaW4h-1
- Prototype mode: https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=7304%3A401368&node-id=7311%3A414747&viewport=534%2C294%2C0.13&scaling=min-zoom&starting-point-node-id=7311%3A414747&show-proto-sidebar=1

![CleanShot 2022-11-29 at 17 01 44](https://user-images.githubusercontent.com/35307309/204580038-8757f19d-482e-4575-b515-0440fe44e14a.png)

**Comment by bedeho** [comment]
Replied on Figma, great work :)

**Comment by toiletgranny** [comment]
Alright, this one is ready to go, then! @DzhideX be sure to enable comments in Figma once you inspect the designs, as I left a few implementation notes/hints for you here and there.

https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=7371%3A390934&t=7WBj0Xw34MBb8p3O-1

**Comment by dmtrjsg** [comment]
Eye candy 👁️ 🍬  Job well done 🙌 

Ready for your magic sir  @DzhideX
