### ISSUE TITLE
Make Mainnet banner more prominent

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#311]
## Context
![Screenshot 2022-11-30 at 15.39.28.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/56a041c8-c07a-4fe9-96a2-94f97dbf5e81)

My reasoning on this is it depends on what sort of information would go into the blog post and whether it would appeal to the new users. If its more prominent, higher ratio will follow the link. 

My subjective take is that I personally totally missed it when reviewing designs in Figma, and even tho on the live build it will be more noticeable with the motion animations that we have on the hero there is a high chance of this banner to be missed. I'd suggest to highlight it more. 

## Scope
- [ ] make banner more prominent

**Comment by toiletgranny** [comment]
@dmtrjsg, @bedeho I cooked up a few alternatives of a different level of prominence, all of which can be reviewed in [this Figma file](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=7641%3A404009&t=ItPpokZzl8oXSGZg-1).
