### ISSUE TITLE
Creator can change the category used in auto-sync from 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/marketing#325]
## Context

Creators can change category from the settings tab that is used in auto-sync

## Scope
- [ ] Create endpoint on the be to update the category fore hte JS channel auto-sync.

**Comment by zeeshanakram3** [comment]
Addressed in #118. Can be done as by sending request to `/ingest` endpoint.

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/youtube-synch #125](https://github.com/Joystream/youtube-synch/issues/125) via [**Zenhub**](https://www.zenhub.com/)
