### ISSUE TITLE
Announce transition policy

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#48]
# Background

https://github.com/Joystream/marketing/issues/40

# Proposal

We need to actually make the announcement, probably with a video, and give a date by which everyone has to have reported their current latest contributions.

**Comment by robertneckelius** [comment]
Will take care of this, @bedeho how/when do I gather all the required info to put this together? Maybe I'll just add it on the marketing call and we can discuss then?

**Comment by robertneckelius** [comment]
@bedeho wrote the blog post, and tweeted yesterday, and i can send out an email on monday. does this suffice for this task, or anything else?
