### ISSUE TITLE
Onboarding Experience Rollout Plan

### ISSUE THREAD

**Issue by mrexpat** [Joystream/marketing#50]
## Requirements / Tasks

- Allow users to go through an experience to educate them on the Joystream projective, and primarily the Founding Members program, with the intention of converting as many high quality contributors as possible.
- Should not require login / account creation (minimal friction)
- Ability to choose avatar / user group (this selection should carry over throughout the experience and dictate user journey)
- Option to change language which takes user to a fully translated version (we will only launch with English, but make any necessary arrangements to easily make the switching of language easy)
- Dynamic user journeys depending on which user group has been selected as their avatar (a video creator does not go through the same journey as a validator).
- First version mobile and desktop, add tablet later
- Written and video content to place inside experience
- List of illustrations for on-page and in-video
- Pulling and displaying data such as bounties, forum posts, proposal count, number of videos, number of channels, total current worker count, openings count
- Dynamic progress bar displayed on each lesson page (depending on which user group has been selected)

## Page Design

Mateusz to create UX / UI in Figma ( https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/?node-id=2468%3A87160 )
- Architecture Map / User Flows
- Lo-Fi Wireframing
- Lo-Fi Prototype
- Drafts of Illustrations (for different contributor roles)
- UI for Video pages
- UI for Conversion pages
- UI for other pages (Modals, Video list)
- Illustrations
- Full Prototype (if needed)
- Video recording (if needed)

## Content Production

- Scripts by Robert
- Recordings by Robert
- Videos to be edited by Sergey
- FAQ list by Robert
- Illustrations for on-page and in-video by Mateusz

## Development

Edvin or possibly DAO contributors to develop the experience, full brief to be created by Robert
FULL BREAK DOWN OF DEV TASKS

## Testing

Robert and people not involved with the project to perform testing

## Deployment

Once tests are completed, and any issues reconciled, deploy the onboarding experience (first page to replace our current /get-started page)

**Comment by traumschule** [comment]
Design is in progress, update based on what is visible in figma. Questions inline.

tasks
- session store for language, role, other info?
- pages
  - Video page: mostly static, FAQ loaded from JSON (`{ question, answer }`)
  - Pick role: static
    - save to local storage without request or user tracking?
    - routing via href and page reload or app router for fast switch?
    - idea: keyboard navigation with arrow keys between roles    
  - Contributor page:
    - TOC (icons) to find info fast?
    - Both `Let us know` and `Ready to work` point to discord. Do you want a fixed footer to not interrupt the page flow?
- needed data:
  - role array: `[ { name, description, logo, become } ]` + selectors for bounties and relevant groups
  - > Pulling and displaying data such as bounties, forum posts, proposal count, number of videos, number of channels, total current worker count, openings count 
  - bounties loaded from json
  - openings are great to see early - loaded from QN, chain or other cache like json that is updated via cronjob?
- roles: user journey: creator, builder, techie, organizer, marketer, curator, (validator?)
  - techie sounds cheap. Do you target `Devops engineer` or `Node operator`?

unclear - needs design
- lesson based progress bar
- List of illustrations for on-page and in-video
- Written and video content to place inside experience
