### ISSUE TITLE
Announce $tJOY reset policy

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#81]
We are going to a fresh chain for `Olympia`, and we will be resetting balances for that chain. Announcement has to be done early in order to give people time to cashout.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703952879841/1201708248375151) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
@bedeho not sure if you are aware but validator unstaked period is 7 days. 29% of issuance is staked for this purpose. So deadline should consider that part

**Comment by singulart** [comment]
I was under impression that it is technically possible to copy over all the balances. Going into Olympia with empty pockets would cause a lot of unnecessary hurdles, like being unable to apply for council, run a validator etc.

**Comment by bedeho** [comment]
> I was under impression that it is technically possible to copy over all the balances. Going into Olympia with empty pockets would cause a lot of unnecessary hurdles, like being unable to apply for council, run a validator etc.

It would not be empty, by resetting, but the current idea is to cap balances to try to avoid the current long-running concentration in $tJOY. Without proper trading venues, which we actually do not even want, this will inevitable happen, and this reset can help counterbalance this.
