### ISSUE TITLE
Solve Discord CAPTCHA friction

### ISSUE THREAD

**Issue by bedeho** [Joystream/marketing#87]
This has been a long running issue, now being mentioned here yet again in light of new influx of users struggeling with CAPTCHA

https://testnet.joystream.org/#/forum/threads/880

A meta issue here is to have better analytics for Discord in general, so we don't have to depend on third parties to raise the issue. Telegram has pretty good built-in analytics.

**Comment by mochet** [comment]
For CAPTCHA I will try to get community involved. Get them to find what is out there

For analytics I saw a pretty interesting tool recently that I will try to find the link for

**Comment by mochet** [comment]
One primary consideration for this, is that it must/really should not use DMs for CAPTCHA verification (our current one does)
* Current crypto projects are heavily suggesting users to disable ALL DMs as a security precaution, so this will act as a barrier for new users.
* Also being a part of crypto servers will often get you frequent spam DMs from people shilling projects/servers.

**Comment by robertneckelius** [comment]
https://captcha.bot/ works in channels, no need for DM.. i just went thru it.. dno how to set it up tho.. @blrhc can you?
